// Bibliothèque complète des actifs naturels — 120+ actifs — disponible OFFLINE
export const ACTIFS = [

  // ══════════════════════════════════════════════════════════════════════════
  // HUILES ESSENTIELLES (A–Z)
  // ══════════════════════════════════════════════════════════════════════════

  { id: 'he_arbre_the', nom: 'Arbre à thé (Tea Tree)', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Antibactérien puissant', 'Antifongique', 'Purifiant pour la peau acnéique', 'Assainissant pour le cuir chevelu', 'Cicatrisant'], utilisations: ['Acné et imperfections', 'Pellicules', 'Mycoses', 'Petites plaies'], dosage: '1 à 2 gouttes dans 5 ml huile végétale. Ne jamais appliquer pur sur peau sensible.', precautions: 'Déconseillé pendant la grossesse. Toujours diluer. Test cutané obligatoire.', origine: 'Australie', odeur: 'Fraîche, camphrée, médicinale', association: ['Lavande vraie', 'Romarin', 'Citron'], tags: ['acné', 'cuir chevelu', 'purifiant', 'antibactérien', 'cicatrisant'] },

  { id: 'he_basilic', nom: 'Basilic tropical', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Anti-spasmodique puissant', 'Tonique nerveux', 'Antalgique', 'Stimulant intellectuel'], utilisations: ['Douleurs musculaires et articulaires', 'Fatigue mentale', 'Spasmes digestifs', 'Maux de tête de tension'], dosage: '2 gouttes dans 10 ml huile végétale pour massage. 2 gouttes en diffusion.', precautions: 'Contre-indiqué grossesse et allaitement. Éviter chez enfants moins de 6 ans. Prudence si épilepsie.', origine: 'Madagascar, Comores', odeur: 'Fraîche, anisée, légèrement épicée', association: ['Menthe poivrée', 'Lavande', 'Citron'], tags: ['muscles', 'fatigue', 'concentration', 'douleurs', 'digestion'] },

  { id: 'he_bergamote', nom: 'Bergamote', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Anti-stress et anxiété', 'Régulateur de l\'humeur', 'Tonifiant cutané', 'Antiseptique léger', 'Antidépresseur naturel'], utilisations: ['Diffusion anti-stress', 'Peau grasse', 'Parfum naturel', 'Déprime légère'], dosage: '3 à 4 gouttes en diffusion. 1 goutte dans 10 ml huile végétale.', precautions: 'PHOTOSENSIBILISANTE — jamais avant exposition solaire. Éviter pendant grossesse.', origine: 'Italie (Calabre)', odeur: 'Fraîche, citronnée, florale', association: ['Lavande', 'Ylang-ylang', 'Géranium'], tags: ['stress', 'anxiété', 'humeur', 'peau grasse', 'antidépresseur'] },

  { id: 'he_bois_santal', nom: 'Bois de santal', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Apaisant et sédatif', 'Hydratant cutané profond', 'Anti-inflammatoire', 'Aphrodisiaque'], utilisations: ['Méditation et relaxation', 'Peaux sèches et matures', 'Diffusion relaxante', 'Parfumerie naturelle'], dosage: '2 gouttes en diffusion. 1 goutte dans 10 ml huile végétale.', precautions: 'Déconseillé pendant grossesse. Excellente tolérance cutanée.', origine: 'Inde, Australie, Nouvelle-Calédonie', odeur: 'Boisée, crémeuse, douce, profonde', association: ['Rose de Damas', 'Néroli', 'Jasmin'], tags: ['relaxation', 'méditation', 'peau sèche', 'aphrodisiaque', 'luxe'] },

  { id: 'he_camomille', nom: 'Camomille romaine', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Apaisante et calmante', 'Anti-inflammatoire', 'Idéale peaux sensibles', 'Aide au sommeil', 'Antispasmodique'], utilisations: ['Peaux sensibles et rouges', 'Stress', 'Troubles du sommeil', 'Irritations cutanées', 'Coliques bébé'], dosage: '1 goutte dans 5 ml huile végétale. 2 gouttes en diffusion le soir.', precautions: 'Déconseillé pendant 1er trimestre grossesse. Allergie possible aux astéracées.', origine: 'France, Grande-Bretagne', odeur: 'Douce, pomme, herbacée', association: ['Rose de Damas', 'Lavande', 'Néroli'], tags: ['peau sensible', 'sommeil', 'stress', 'apaisant', 'bébé'] },

  { id: 'he_cannelle_ceylan', nom: 'Cannelle de Ceylan (écorce)', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Antibactérienne très puissante', 'Stimulante générale', 'Soutien dans le sevrage des addictions', 'Antiparasitaire', 'Tonique nerveux et sexuel'], utilisations: ['Soutien à l\'arrêt du tabac et addictions', 'Infections résistantes', 'Fatigue profonde', 'Diffusion atmosphère chaleureuse (très diluée)'], dosage: '1 goutte dans 20 ml huile végétale MAXIMUM. 1 goutte en diffusion mélangée à des agrumes (jamais seule).', precautions: 'TRÈS DERMOCAUSTIQUE — dilution maximale obligatoire, jamais pure sur peau. Contre-indiquée grossesse, allaitement, enfants moins de 12 ans, anticoagulants, hypertension. Test cutané impératif.', origine: 'Sri Lanka (Ceylan), Madagascar', odeur: 'Épicée chaude, sucrée, boisée, intense', association: ['Orange douce', 'Gingembre', 'Clou de girofle'], tags: ['addictions', 'tabac', 'antibactérien', 'stimulant', 'précautions'] },

  { id: 'he_cede', nom: 'Cèdre de l\'Atlas', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Anti-chute capillaire', 'Lipolytique (cellulite)', 'Veineux', 'Apaisant profond', 'Drainant lymphatique'], utilisations: ['Chute de cheveux', 'Cellulite', 'Stress et anxiété', 'Diffusion apaisante', 'Rétention d\'eau'], dosage: '3 gouttes dans 15 ml huile végétale. 3 gouttes en diffusion.', precautions: 'Contre-indiqué grossesse et enfants moins de 12 ans. Épilepsie.', origine: 'Maroc (Moyen Atlas)', odeur: 'Boisée, chaude, légèrement camphrée', association: ['Romarin', 'Lavande', 'Cyprès'], tags: ['cheveux', 'anti-chute', 'cellulite', 'minceur', 'drainage'] },

  { id: 'he_citron', nom: 'Citron', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Purifiant et astringent', 'Éclat du teint', 'Tonifiant', 'Antibactérien', 'Stimulant immunitaire'], utilisations: ['Teint terne', 'Peaux grasses', 'Diffusion purifiante', 'Taches pigmentaires'], dosage: '1 goutte dans 10 ml huile végétale. 3 à 5 gouttes en diffusion.', precautions: 'PHOTOSENSIBILISANT — jamais avant exposition solaire. Déconseillé pendant grossesse.', origine: 'Italie, Espagne', odeur: 'Fraîche, acidulée, citronnée', association: ['Bergamote', 'Lavande', 'Tea Tree'], tags: ['éclat', 'teint', 'purifiant', 'peau grasse', 'taches'] },

  { id: 'he_citronnelle', nom: 'Citronnelle de Java', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Anti-moustiques naturel', 'Anti-inflammatoire', 'Tonifiant musculaire', 'Assainissant de l\'air'], utilisations: ['Répulsif insectes naturel', 'Douleurs articulaires', 'Diffusion purifiante', 'Courbatures'], dosage: '5 gouttes en diffusion. 3 gouttes dans 10 ml huile végétale pour massage.', precautions: 'Déconseillé grossesse. Peut irriter peaux sensibles. Toujours diluer.', origine: 'Indonésie, Java', odeur: 'Citronnée puissante, fraîche, herbacée', association: ['Eucalyptus', 'Lavande', 'Tea Tree'], tags: ['insectes', 'répulsif', 'douleurs', 'articulations', 'muscles'] },

  { id: 'he_clou_girofle', nom: 'Clou de girofle', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Antibactérien très puissant', 'Antalgique local', 'Antifongique', 'Antiparasitaire'], utilisations: ['Douleurs dentaires', 'Infections cutanées', 'Mycoses', 'Usage ultra-dilué en cuisine'], dosage: '1 goutte dans 20 ml huile végétale MAXIMUM. Très dermocaustique pur.', precautions: 'TRÈS IRRITANT — dilution maximale obligatoire. Contre-indiqué grossesse, enfants, anticoagulants.', origine: 'Madagascar, Zanzibar, Indonésie', odeur: 'Épicée très puissante, chaude, eugenol', association: ['Thym', 'Lavande', 'Citron'], tags: ['antibactérien', 'douleur dentaire', 'antifongique', 'puissant', 'précautions'] },

  { id: 'he_cypres', nom: 'Cyprès toujours vert', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Veineux et drainant', 'Anti-transpirant naturel', 'Astringent', 'Contre la cellulite', 'Tonifiant respiratoire'], utilisations: ['Jambes lourdes', 'Varices', 'Transpiration excessive', 'Cellulite', 'Toux'], dosage: '3 à 5 gouttes dans 20 ml huile végétale pour massage des jambes.', precautions: 'Contre-indiqué grossesse, cancer hormono-dépendant.', origine: 'France, Espagne', odeur: 'Boisée, fraîche, résineuse', association: ['Cèdre', 'Citron', 'Menthe'], tags: ['jambes', 'drainage', 'cellulite', 'minceur', 'circulation', 'varices'] },

  { id: 'he_encens', nom: 'Encens (oliban)', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Régénérant cellulaire exceptionnel', 'Anti-rides profond', 'Apaisant et méditatif', 'Immunostimulant'], utilisations: ['Soins anti-âge intensifs', 'Cicatrices et vergetures', 'Méditation', 'Peaux matures'], dosage: '1 goutte dans 10 ml huile végétale précieuse. 2 gouttes en diffusion.', precautions: 'Déconseillé pendant grossesse. Excellente tolérance cutanée.', origine: 'Somalie, Éthiopie, Oman', odeur: 'Résineuse, boisée, légèrement camphrée', association: ['Rose de Damas', 'Argan HV', 'Néroli'], tags: ['anti-rides', 'peau mature', 'méditation', 'cicatrices', 'régénérant'] },

  { id: 'he_eucalyptus', nom: 'Eucalyptus radié', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Décongestionnant respiratoire', 'Antibactérien', 'Antiviral', 'Stimulant immunitaire', 'Antitussif'], utilisations: ['Rhumes et infections respiratoires', 'Diffusion assainissante', 'Muscles fatigués', 'Sinusites'], dosage: '3 à 5 gouttes en diffusion 20 min max. 2 gouttes dans 10 ml huile pour massage thoracique.', precautions: 'Interdit enfants moins de 6 ans. Déconseillé grossesse et allaitement.', origine: 'Australie, Espagne', odeur: 'Fraîche, camphrée, mentholée', association: ['Thym', 'Lavande', 'Citron'], tags: ['respiratoire', 'antiviral', 'immunitaire', 'rhume', 'sinus'] },

  { id: 'he_geranium', nom: 'Géranium rosat', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Rééquilibrant hormonal', 'Astringent et tonifiant cutané', 'Cicatrisant', 'Anti-stress', 'Anti-inflammatoire'], utilisations: ['Peaux mixtes et grasses', 'Déséquilibres hormonaux', 'Cicatrices et vergetures', 'Stress'], dosage: '1 à 2 gouttes dans 5 ml huile végétale. 3 gouttes en diffusion.', precautions: 'Déconseillé 3 premiers mois grossesse. Interaction possible avec anticoagulants.', origine: 'Égypte, Madagascar, Réunion', odeur: 'Florale, rosée, légèrement mentholée', association: ['Rose de Damas', 'Ylang-ylang', 'Lavande'], tags: ['hormones', 'peau mixte', 'cicatrisant', 'stress', 'tonus'] },

  { id: 'he_gingembre', nom: 'Gingembre', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Stimulant circulatoire et digestif', 'Réchauffant', 'Anti-nauséeux', 'Tonifiant musculaire', 'Aphrodisiaque'], utilisations: ['Nausées et maux de transport', 'Douleurs articulaires', 'Jambes lourdes', 'Digestion difficile', 'Fatigue profonde'], dosage: '2 gouttes dans 10 ml huile végétale. 2 gouttes en diffusion.', precautions: 'Peut être irritant pour peau sensible. Déconseillé grossesse et anticoagulants.', origine: 'Inde, Madagascar, Sri Lanka', odeur: 'Épicée chaude, citronnée, légèrement poivrée', association: ['Citron', 'Menthe poivrée', 'Cardamome'], tags: ['nausées', 'circulation', 'digestion', 'muscles', 'énergie', 'aphrodisiaque'] },

  { id: 'he_helichryse', nom: 'Hélichryse italienne (immortelle)', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Anti-hématomes exceptionnel', 'Régénérant cutané profond', 'Anti-cicatrices', 'Anti-inflammatoire', 'Anti-âge'], utilisations: ['Coups et hématomes', 'Cicatrices récentes', 'Couperose', 'Peaux matures', 'Après chirurgie'], dosage: '1 à 2 gouttes dans 5 ml huile végétale (rose musquée idéalement).', precautions: 'Déconseillé si prise d\'anticoagulants. Éviter 1er trimestre grossesse.', origine: 'France, Corse, Balkans', odeur: 'Miel, camomille, légèrement épicée', association: ['Rose musquée HV', 'Argan HV', 'Lavande'], tags: ['hématomes', 'cicatrices', 'couperose', 'anti-âge', 'coups'] },

  { id: 'he_jasmin', nom: 'Jasmin absolu', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Antidépresseur et euphorisant', 'Aphrodisiaque profond', 'Adoucissant cutané', 'Calmant nerveux'], utilisations: ['Déprime et anxiété', 'Parfumerie naturelle de luxe', 'Peaux sèches et sensibles', 'Stress émotionnel'], dosage: '1 goutte dans 20 ml huile végétale. Très concentré et coûteux.', precautions: 'Peut provoquer des maux de tête à haute dose. Éviter pendant grossesse.', origine: 'Égypte, Inde, Maroc', odeur: 'Florale intense, envoûtante, douce', association: ['Rose de Damas', 'Santal', 'Ylang-ylang'], tags: ['antidépresseur', 'aphrodisiaque', 'anxiété', 'luxe', 'parfum'] },

  { id: 'he_juniperus', nom: 'Genévrier (baies)', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Diurétique et drainant', 'Purifiant et détoxifiant', 'Anti-rhumatismal', 'Tonifiant cutané'], utilisations: ['Rétention d\'eau', 'Cellulite', 'Drainage corporel', 'Peaux à imperfections', 'Douleurs articulaires'], dosage: '3 gouttes dans 15 ml huile végétale pour massage drainant.', precautions: 'Contre-indiqué si maladie rénale, grossesse. Ne pas utiliser plus de 3 semaines.', origine: 'France, Italie, Maroc', odeur: 'Fraîche, boisée, légèrement poivrée', association: ['Cyprès', 'Citron', 'Cèdre'], tags: ['drainant', 'cellulite', 'rétention', 'détox', 'minceur'] },

  { id: 'he_lavande', nom: 'Lavande vraie (fine)', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Apaisante et relaxante', 'Cicatrisante', 'Antibactérienne', 'Aide au sommeil', 'Analgésique'], utilisations: ['Stress et anxiété', 'Sommeil', 'Brûlures légères et coups de soleil', 'Piqûres d\'insectes', 'Maux de tête'], dosage: 'Peut s\'utiliser pure sur petite surface. 2 à 3 gouttes en diffusion. 1 goutte sur l\'oreiller.', precautions: 'Éviter 1er trimestre grossesse par précaution. Généralement très bien tolérée.', origine: 'France (Provence, altitude)', odeur: 'Florale, herbacée, douce', association: ['Camomille romaine', 'Tea Tree', 'Ylang-ylang'], tags: ['sommeil', 'stress', 'cicatrisant', 'brûlures', 'polyvalent', 'apaisant'] },

  { id: 'he_lavande_aspic', nom: 'Lavande aspic', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Anti-venimeux', 'Cicatrisante rapide', 'Anti-inflammatoire puissant', 'Antalgique local'], utilisations: ['Piqûres d\'abeilles et guêpes', 'Brûlures et coups de soleil', 'Démangeaisons', 'Cicatrisation rapide'], dosage: '1 à 2 gouttes pures sur la zone atteinte uniquement. Jamais en diffusion prolongée.', precautions: 'Différente de la lavande vraie — ne pas confondre. Contre-indiqué grossesse et épilepsie.', origine: 'France, Espagne (altitude)', odeur: 'Camphrée, fraîche, plus forte que lavande fine', association: ['Tea Tree', 'Calendula HV'], tags: ['piqûres', 'brûlures', 'cicatrisation', 'urgence', 'venimeux'] },

  { id: 'he_lemon_grass', nom: 'Lemongrass (verveine des Indes)', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Tonifiant et revitalisant', 'Anti-douleur musculaire', 'Répulsif insectes', 'Anti-cellulite', 'Tonifiant cutané pores'], utilisations: ['Muscles fatigués', 'Cellulite', 'Pores dilatés', 'Répulsif naturel', 'Diffusion tonifiante'], dosage: '2 gouttes dans 10 ml huile végétale. 3 gouttes en diffusion max.', precautions: 'Peut irriter peaux sensibles. Déconseillé grossesse. Toujours diluer.', origine: 'Inde, Madagascar, Guatemala', odeur: 'Citronnée puissante, fraîche, herbacée', association: ['Géranium', 'Tea Tree', 'Cèdre'], tags: ['muscles', 'cellulite', 'pores', 'insectes', 'tonifiant'] },

  { id: 'he_mandarine', nom: 'Mandarine rouge', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Calmante et sédative légère', 'Régulateur du sommeil', 'Anti-vergetures', 'Digestive', 'Apaisante enfants'], utilisations: ['Stress chez enfants et adultes', 'Difficultés d\'endormissement', 'Vergetures (prévention)', 'Digestion'], dosage: '3 à 4 gouttes en diffusion. 1 goutte dans 5 ml huile végétale.', precautions: 'Peut être légèrement photosensibilisant. Éviter exposition solaire après application.', origine: 'Italie, Espagne, Brésil', odeur: 'Douce, sucrée, agrumes, chaleureuse', association: ['Lavande', 'Camomille romaine', 'Ylang-ylang'], tags: ['sommeil', 'stress', 'vergetures', 'enfants', 'digestion'] },

  { id: 'he_marjolaine', nom: 'Marjolaine à coquilles', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Calmante puissante du système nerveux', 'Aide à l\'endormissement profond', 'Antispasmodique', 'Régulatrice de la tension artérielle', 'Anaphrodisiaque (apaise les compulsions)'], utilisations: ['Insomnies et troubles du sommeil', 'Anxiété chronique', 'Hypertension légère', 'Spasmes digestifs', 'Surmenage mental et burn-out'], dosage: '2 gouttes dans 10 ml huile végétale en massage du plexus solaire ou plante des pieds. 3 gouttes en diffusion 30 min avant le coucher.', precautions: 'Contre-indiquée grossesse et allaitement. Éviter chez enfants moins de 6 ans. Hypotensive — prudence si hypotension. Ne pas utiliser le matin (sédative).', origine: 'Égypte, Espagne, France', odeur: 'Herbacée, chaude, légèrement camphrée, douce', association: ['Lavande vraie', 'Camomille romaine', 'Mandarine'], tags: ['sommeil', 'insomnie', 'anxiété', 'tension', 'apaisant', 'plexus', 'burn-out'] },

  { id: 'he_menthe', nom: 'Menthe poivrée', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Stimulante et tonifiante', 'Rafraîchissante', 'Anti-douleur', 'Digestive', 'Contre la fatigue'], utilisations: ['Maux de tête (tempes)', 'Fatigue mentale', 'Nausées', 'Douleurs musculaires', 'Diffusion énergisante'], dosage: '1 goutte sur les tempes (éviter contact yeux). 2 gouttes en diffusion 15 min.', precautions: 'INTERDIT enfants moins de 7 ans et femmes enceintes. Contre-indiquée si épilepsie.', origine: 'France, Maroc, USA', odeur: 'Très fraîche, mentholée, puissante', association: ['Eucalyptus', 'Citron', 'Romarin'], tags: ['énergie', 'fatigue', 'maux de tête', 'douleurs', 'nausées'] },

  { id: 'he_menthe_verte', nom: 'Menthe verte (spearmint)', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Plus douce que menthe poivrée', 'Digestive', 'Rafraîchissante', 'Déodorante', 'Anti-nausées'], utilisations: ['Digestion difficile', 'Nausées légères', 'Haleine fraîche', 'Diffusion tonifiante douce'], dosage: '3 gouttes en diffusion. 2 gouttes dans 10 ml huile végétale.', precautions: 'Plus douce que menthe poivrée. Déconseillé grossesse. Convient mieux aux sensibilités.', origine: 'France, USA, Inde', odeur: 'Fraîche, douce, légèrement sucrée', association: ['Citron', 'Eucalyptus', 'Lavande'], tags: ['digestion', 'nausées', 'fraîcheur', 'doux', 'haleine'] },

  { id: 'he_myrrhe', nom: 'Myrrhe', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Cicatrisante et régénérante', 'Anti-inflammatoire', 'Anti-âge', 'Antiseptique', 'Astringente'], utilisations: ['Peaux matures et rides', 'Cicatrices et fissures', 'Soins bucco-dentaires', 'Gencives douloureuses'], dosage: '1 à 2 gouttes dans 10 ml huile végétale. Très épaisse — chauffer légèrement.', precautions: 'Contre-indiqué grossesse. Peut être irritante à haute dose.', origine: 'Somalie, Yémen, Éthiopie', odeur: 'Résineuse, terreuse, chaude, amère', association: ['Encens', 'Santal', 'Rose musquée HV'], tags: ['anti-rides', 'cicatrices', 'peau mature', 'gencives', 'antiseptique'] },

  { id: 'he_neroli', nom: 'Néroli (fleur d\'oranger)', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Antidépresseur naturel', 'Régénérant cutané', 'Anti-rides', 'Calmant du système nerveux', 'Régulateur du rythme cardiaque'], utilisations: ['Peaux matures et rides', 'Anxiété et déprime', 'Cicatrices et vergetures', 'Parfum naturel de luxe', 'Stress intense'], dosage: '1 goutte dans 10 ml huile végétale précieuse. Très concentré.', precautions: 'Peu de contre-indications. Éviter 1er trimestre grossesse.', origine: 'Tunisie, Maroc, France', odeur: 'Florale intense, miel, légèrement citronnée', association: ['Rose de Damas', 'Jasmin', 'Géranium'], tags: ['anti-rides', 'peau mature', 'anxiété', 'déprime', 'luxe', 'vergetures'] },

  { id: 'he_niaouli', nom: 'Niaouli', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Immunostimulant puissant', 'Antiviral', 'Décongestionnant respiratoire', 'Cicatrisant cutané', 'Radioprotecteur'], utilisations: ['Infections respiratoires', 'Hiver et immunité', 'Cicatrisation post-opératoire', 'Acné', 'Radiochimiothérapie (usage médical)'], dosage: '2 à 3 gouttes dans 10 ml huile végétale. 4 gouttes en diffusion.', precautions: 'Déconseillé si cancers hormono-dépendants. Éviter grossesse 1er trimestre.', origine: 'Nouvelle-Calédonie, Madagascar', odeur: 'Fraîche, camphrée, eucalyptus-like', association: ['Eucalyptus', 'Tea Tree', 'Ravintsara'], tags: ['immunité', 'antiviral', 'respiratoire', 'cicatrisant', 'hiver'] },

  { id: 'he_orange_douce', nom: 'Orange douce', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Anxiolytique doux', 'Antidépresseur léger', 'Digestive', 'Apaisante enfants', 'Parfumante'], utilisations: ['Anxiété et stress léger', 'Digestion difficile', 'Atmosphère joyeuse en diffusion', 'Enfants nerveux'], dosage: '4 à 5 gouttes en diffusion. 2 gouttes dans 10 ml huile végétale.', precautions: 'Légèrement photosensibilisante. Éviter avant exposition solaire.', origine: 'Espagne, Brésil, Italie', odeur: 'Douce, sucrée, fruitée, familière', association: ['Cannelle', 'Vanille', 'Gingembre'], tags: ['anxiété', 'bonne humeur', 'digestion', 'enfants', 'douceur'] },

  { id: 'he_palmarosa', nom: 'Palmarosa', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Hydratant cutané', 'Rééquilibrant du sébum', 'Antibactérien', 'Cicatrisant', 'Antifongique léger'], utilisations: ['Peaux sèches et déshydratées', 'Acné', 'Infections cutanées', 'Soins capillaires'], dosage: '1 à 2 gouttes dans 5 ml huile végétale.', precautions: 'Déconseillé 1er trimestre grossesse. Bonne tolérance cutanée.', origine: 'Inde, Vietnam, Madagascar', odeur: 'Florale, rosée, légèrement citronnée', association: ['Géranium', 'Tea Tree', 'Lavande'], tags: ['hydratation', 'peau sèche', 'sébum', 'acné', 'antifongique'] },

  { id: 'he_pamplemousse', nom: 'Pamplemousse', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Tonifiante et énergisante', 'Anti-déprime saisonnière', 'Drainante et lipolytique', 'Stimulante de l\'humeur', 'Coupe-faim émotionnel'], utilisations: ['Humeur basse en hiver', 'Fatigue chronique au réveil', 'Cellulite et drainage', 'Diffusion énergisante du matin', 'Compulsions alimentaires'], dosage: '4 à 5 gouttes en diffusion le matin (15 à 20 min). 3 gouttes dans 15 ml huile végétale pour massage drainant.', precautions: 'PHOTOSENSIBILISANTE — jamais avant exposition solaire (au moins 8h après application cutanée). Déconseillée 1er trimestre grossesse. Conserver au frais (s\'oxyde).', origine: 'USA (Floride, Californie), Israël', odeur: 'Fraîche, pétillante, agrumes amers', association: ['Bergamote', 'Citron', 'Romarin'], tags: ['humeur', 'hiver', 'énergie', 'drainage', 'cellulite', 'compulsions'] },

  { id: 'he_petitgrain', nom: 'Petitgrain bigarade', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Régulateur du système nerveux', 'Déodorant naturel puissant', 'Anti-transpiration', 'Apaisant', 'Tonifiant cutané'], utilisations: ['Transpiration excessive', 'Stress et nervosité', 'Troubles du sommeil', 'Soins peaux grasses'], dosage: '3 gouttes dans 10 ml huile végétale. 4 gouttes en diffusion.', precautions: 'Excellente tolérance. Déconseillé pendant grossesse par précaution.', origine: 'Paraguay, France, Algérie', odeur: 'Fraîche, boisée, légèrement fleurie', association: ['Bergamote', 'Lavande', 'Ylang-ylang'], tags: ['transpiration', 'déodorant', 'stress', 'nervosité', 'peau grasse'] },

  { id: 'he_piment_doux', nom: 'Piment doux (graine)', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Stimulant circulatoire puissant', 'Réchauffant', 'Anti-douleur rhumatismal', 'Aphrodisiaque'], utilisations: ['Douleurs articulaires', 'Mauvaise circulation', 'Mains et pieds froids', 'Courbatures'], dosage: '1 goutte dans 20 ml huile végétale. Très chaud — tester en petite quantité.', precautions: 'Très irritant — dilution maximale. Éviter zones sensibles. Contre-indiqué grossesse.', origine: 'Jamaïque, Mexique', odeur: 'Épicée chaude, cannelle-like, poivrée', association: ['Gingembre', 'Cyprès', 'Citron'], tags: ['circulation', 'froid', 'rhumatismes', 'douleurs', 'réchauffant'] },

  { id: 'he_poivre_noir', nom: 'Poivre noir (Piper nigrum)', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Anti-tabac : réduit le craving (référence Franchomme)', 'Stimulante digestive', 'Antalgique articulaire et musculaire', 'Réchauffante', 'Tonifiante mentale'], utilisations: ['Sevrage tabagique en olfaction', 'Douleurs articulaires et musculaires', 'Digestion lente', 'Mains et pieds froids', 'Fatigue mentale'], dosage: '1 à 2 gouttes en olfaction sèche au flacon lors d\'une envie de cigarette. 2 gouttes dans 10 ml huile végétale pour massage articulaire.', precautions: 'Déconseillée pendant grossesse et allaitement. Peut irriter peaux sensibles — toujours diluer pour usage cutané. Éviter avant le coucher (stimulante).', origine: 'Inde (Kerala), Madagascar, Sri Lanka', odeur: 'Épicée puissante, poivrée, légèrement boisée', association: ['Citron', 'Pamplemousse', 'Gingembre'], tags: ['arrêt tabac', 'sevrage', 'craving', 'douleurs', 'digestion', 'olfaction'] },

  { id: 'he_ravintsara', nom: 'Ravintsara', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Antiviral exceptionnel', 'Immunostimulant', 'Expectorant', 'Tonifiant nerveux', 'Anti-fatigue'], utilisations: ['Infections virales (rhumes, grippe)', 'Fatigue chronique', 'Renforcement hivernal de l\'immunité', 'Herpès'], dosage: '3 gouttes dans 10 ml huile végétale. 5 gouttes en diffusion.', precautions: 'Bien toléré. Déconseillé grossesse 1er trimestre. À différencier du ravensare.', origine: 'Madagascar', odeur: 'Fraîche, camphrée, légèrement anisée', association: ['Eucalyptus radié', 'Tea Tree', 'Niaouli'], tags: ['antiviral', 'grippe', 'immunité', 'hiver', 'fatigue', 'herpès'] },

  { id: 'he_romarin', nom: 'Romarin à cinéole', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Stimulant du cuir chevelu', 'Anti-chute', 'Tonifiant', 'Purifiant', 'Stimulant circulatoire', 'Concentration'], utilisations: ['Chute de cheveux', 'Cheveux gras', 'Diffusion revitalisante', 'Mémoire et concentration', 'Fatigue intellectuelle'], dosage: '2 à 3 gouttes dans 15 ml huile végétale pour cuir chevelu. 3 gouttes en diffusion.', precautions: 'Contre-indiqué grossesse, épilepsie, hypertension.', origine: 'France, Espagne, Maroc', odeur: 'Fraîche, camphrée, herbacée', association: ['Cèdre de l\'Atlas', 'Tea Tree', 'Ylang-ylang'], tags: ['cheveux', 'anti-chute', 'cuir chevelu', 'concentration', 'mémoire'] },

  { id: 'he_rose', nom: 'Rose de Damas', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Régénérant cellulaire exceptionnel', 'Anti-rides', 'Hydratant', 'Antidépresseur', 'Aphrodisiaque'], utilisations: ['Peaux matures', 'Anti-âge', 'Stress émotionnel profond', 'Parfum de luxe', 'Deuil et traumatismes'], dosage: '1 goutte dans 10 ml huile végétale. Très précieux — utiliser avec parcimonie.', precautions: 'Éviter 1er trimestre grossesse. L\'huile la plus précieuse au monde.', origine: 'Bulgarie, Turquie, Maroc', odeur: 'Rose intense, miel, boisée', association: ['Néroli', 'Géranium', 'Bois de santal'], tags: ['anti-rides', 'peau mature', 'luxe', 'émotionnel', 'deuil', 'aphrodisiaque'] },

  { id: 'he_sauge_sclarée', nom: 'Sauge sclarée', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Régulateur hormonal féminin', 'Anti-sudoripare', 'Antispasmodique', 'Euphorisant', 'Régénérant cutané'], utilisations: ['Cycles menstruels irréguliers', 'Transpiration excessive', 'Péri-ménopause', 'Stress et déprime'], dosage: '2 gouttes dans 10 ml huile végétale. 3 gouttes en diffusion.', precautions: 'Contre-indiqué grossesse, allaitement, cancers hormono-dépendants. Prudence si alcool.', origine: 'France, Russie, USA', odeur: 'Florale, herbacée, légèrement musquée', association: ['Géranium', 'Bergamote', 'Lavande'], tags: ['hormones', 'règles', 'ménopause', 'transpiration', 'déprime'] },

  { id: 'he_thym_linalol', nom: 'Thym à linalol', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Antibactérien doux', 'Antifongique', 'Immunostimulant', 'Idéal enfants et femmes enceintes', 'Tonifiant'], utilisations: ['Infections ORL bénignes', 'Mycoses douces', 'Renforcement immunitaire', 'Enfants (après 6 ans)'], dosage: '2 à 3 gouttes dans 10 ml huile végétale. 3 gouttes en diffusion.', precautions: 'Le plus doux des thyms. Peut être utilisé pendant grossesse (2e et 3e trimestres avec prudence).', origine: 'France (Provence, Maroc)', odeur: 'Florale, douce, légèrement herbacée', association: ['Eucalyptus', 'Ravintsara', 'Lavande'], tags: ['antibactérien', 'immunité', 'enfants', 'doux', 'antifongique'] },

  { id: 'he_thuya', nom: 'Thuya (cèdre de l\'Est)', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Anti-verrue', 'Antifongique', 'Astringent'], utilisations: ['Verrues (usage très dilué)', 'Mycoses'], dosage: '1 goutte pure sur la verrue uniquement — usage très localisé.', precautions: 'TOXIQUE — usage externe localisé uniquement. Contre-indiqué grossesse, enfants, épilepsie.', origine: 'Canada, USA', odeur: 'Camphrée, boisée, forte', association: [], tags: ['verrues', 'antifongique', 'précautions', 'localisé'] },

  { id: 'he_vetiver', nom: 'Vétiver', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Ancrant et stabilisant', 'Anti-stress profond', 'Circulatoire', 'Régénérant cutané', 'Aphrodisiaque'], utilisations: ['Anxiété profonde et burn-out', 'Méditation et ancrage', 'Peaux grasses', 'Couperose'], dosage: '1 à 2 gouttes en diffusion (puissant). 1 goutte dans 10 ml huile végétale.', precautions: 'Déconseillé grossesse. Très visqueux — diluer dans alcool ou huile chaude.', origine: 'Haïti, Indonésie, Inde', odeur: 'Terreuse, boisée, fumée, profonde', association: ['Santal', 'Encens', 'Bergamote'], tags: ['anxiété', 'burn-out', 'ancrage', 'méditation', 'couperose'] },

  { id: 'he_ylang', nom: 'Ylang-ylang', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Rééquilibrant sébacé', 'Aphrodisiaque', 'Anti-stress profond', 'Soin cheveux brillants', 'Antidépresseur', 'Anti-hypertenseur'], utilisations: ['Cheveux brillants et nourris', 'Stress et tensions', 'Diffusion relaxante', 'Peaux mixtes', 'Hypertension légère'], dosage: '1 goutte maximum en diffusion. 1 goutte dans 10 ml huile pour cheveux.', precautions: 'Très puissant — doses minimales. Peut provoquer maux de tête si surdosé.', origine: 'Madagascar, Comores, Philippines', odeur: 'Florale intense, exotique, sucrée', association: ['Bergamote', 'Géranium', 'Bois de santal'], tags: ['cheveux', 'brillance', 'stress', 'sébum', 'aphrodisiaque', 'hypertension'] },


  { id: 'he_bois_rose', nom: 'Bois de rose', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Régénérant cutané puissant', 'Anti-rides', 'Cicatrisant', 'Tonique cutané doux', 'Anti-bactérien'], utilisations: ['Peaux matures', 'Vergetures', 'Cicatrices', 'Soin nuit régénérant'], dosage: '1 à 2 gouttes dans 5 ml huile végétale.', precautions: 'Espèce menacée — préférer le Bois de Hô (composition similaire). Excellente tolérance.', origine: 'Brésil, Pérou', odeur: 'Florale, boisée, douce', association: ['Rose musquée HV', 'Argan HV', 'Géranium HE'], tags: ['anti-rides', 'régénérant', 'peau mature', 'cicatrices', 'vergetures'] },

  { id: 'he_bois_ho', nom: 'Bois de Hô', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Régénérant cutané', 'Anti-rides', 'Tonique cutané', 'Apaisant', 'Antibactérien'], utilisations: ['Peaux matures', 'Cicatrices et vergetures', 'Soin visage régénérant', 'Diffusion apaisante'], dosage: '1 à 2 gouttes dans 5 ml huile végétale.', precautions: 'Alternative écologique au Bois de Rose. Déconseillé 1er trimestre grossesse.', origine: 'Chine, Vietnam', odeur: 'Florale, boisée, légèrement camphrée', association: ['Rose musquée HV', 'Argan HV', 'Néroli HE'], tags: ['anti-rides', 'régénérant', 'peau mature', 'cicatrices', 'écologique'] },

  { id: 'he_patchouli', nom: 'Patchouli', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Régénérant cutané', 'Anti-cellulite et drainant', 'Tonique veineux', 'Cicatrisant', 'Anti-inflammatoire'], utilisations: ['Cellulite et peau d\'orange', 'Jambes lourdes', 'Cicatrices anciennes', 'Peaux abîmées', 'Parfumerie'], dosage: '3 à 5 gouttes dans 15 ml huile végétale pour massage drainant.', precautions: 'Très bien toléré. Déconseillé pendant grossesse 1er trimestre.', origine: 'Indonésie, Inde, Madagascar', odeur: 'Boisée, terreuse, orientale, profonde', association: ['Cèdre HE', 'Cyprès HE', 'Géranium HE'], tags: ['cellulite', 'minceur', 'drainage', 'cicatrices', 'parfum'] },

  { id: 'he_ciste', nom: 'Ciste ladanifère', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Cicatrisant exceptionnel', 'Anti-rides puissant', 'Astringent', 'Hémostatique (saignements)', 'Régénérant cellulaire'], utilisations: ['Soins anti-âge intensifs', 'Cicatrices récentes', 'Couperose', 'Petits saignements', 'Peaux matures fragiles'], dosage: '1 goutte dans 10 ml huile végétale précieuse. Très puissant.', precautions: 'Contre-indiqué grossesse, allaitement, traitements anticoagulants.', origine: 'Espagne, Maroc, Portugal', odeur: 'Résineuse, ambrée, chaude', association: ['Hélichryse HE', 'Rose musquée HV', 'Encens HE'], tags: ['anti-rides', 'cicatrices', 'couperose', 'peau mature', 'régénérant'] },

  { id: 'he_pin_sylvestre', nom: 'Pin sylvestre', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Tonique général', 'Décongestionnant respiratoire', 'Cortisone-like (énergie)', 'Antiseptique atmosphérique', 'Anti-fatigue profonde'], utilisations: ['Fatigue chronique', 'Diffusion purifiante', 'Soins cuir chevelu (pellicules)', 'Hiver et immunité'], dosage: '3 gouttes dans 10 ml huile végétale. 5 gouttes en diffusion.', precautions: 'Contre-indiqué grossesse, allaitement, hypertension. Possible irritation cutanée.', origine: 'France, Russie, Scandinavie', odeur: 'Résineuse, fraîche, forêt', association: ['Eucalyptus HE', 'Romarin HE', 'Cèdre HE'], tags: ['fatigue', 'énergie', 'respiratoire', 'cuir chevelu', 'hiver'] },

  { id: 'he_epinette_noire', nom: 'Épinette noire', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Tonique surrénale puissant', 'Anti-fatigue intense', 'Décongestionnant respiratoire', 'Antibactérien', 'Cortisone-like'], utilisations: ['Burn-out et fatigue chronique', 'Diffusion énergisante matin', 'Massage tonifiant', 'Hiver immunitaire'], dosage: '2 à 3 gouttes dans 10 ml huile végétale (massage bas du dos). 4 gouttes en diffusion.', precautions: 'Contre-indiqué grossesse, allaitement, enfants moins de 6 ans, hypertension.', origine: 'Canada (Québec)', odeur: 'Résineuse, fraîche, conifère', association: ['Pin sylvestre HE', 'Romarin HE', 'Menthe poivrée HE'], tags: ['fatigue', 'burn-out', 'énergie', 'surrénales', 'hiver'] },

  { id: 'he_laurier_noble', nom: 'Laurier noble', type: 'Huile essentielle', categorie: 'HE', bienfaits: ['Antiviral et antibactérien', 'Antifongique', 'Confiance en soi (psyché)', 'Anti-douleur', 'Lymphatique'], utilisations: ['Soins bouche (aphtes, gencives)', 'Mycoses', 'Diffusion confiance avant prise de parole', 'Acné'], dosage: '1 goutte dans 10 ml huile végétale. 2 gouttes en diffusion (puissant).', precautions: 'Contre-indiqué grossesse, allaitement, asthme, allergies aux lauracées.', origine: 'France, Croatie, Maroc', odeur: 'Aromatique, herbacée, légèrement épicée', association: ['Tea Tree HE', 'Lavande HE', 'Ravintsara HE'], tags: ['antiviral', 'aphtes', 'mycoses', 'confiance', 'acné'] },

  // ══════════════════════════════════════════════════════════════════════════
  // HUILES VÉGÉTALES (A–Z)
  // ══════════════════════════════════════════════════════════════════════════

  { id: 'hv_amande', nom: 'Amande douce', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Émolliente et adoucissante', 'Nourrissante', 'Apaisante peaux sensibles', 'Légère et bien tolérée', 'Anti-démangeaisons'], utilisations: ['Huile base universelle', 'Peaux sèches et sensibles', 'Soin bébé', 'Démaquillage', 'Massage'], dosage: 'Utiliser pure à 100%. Idéale comme base pour diluer les HE.', precautions: 'Allergie aux fruits à coque possible.', origine: 'Espagne, Italie, Californie', odeur: 'Légèrement sucrée, subtile', association: ['Toutes les HE', 'Rose musquée HV', 'Vitamine E'], tags: ['peau sensible', 'base', 'nourrissant', 'bébé', 'massage', 'démaquillage'] },

  { id: 'hv_argousier', nom: 'Argousier', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Régénérant cutané exceptionnel', 'Anti-âge très concentré', 'Cicatrisant', 'Anti-inflammatoire', 'Riche en bêta-carotène'], utilisations: ['Anti-âge intensif', 'Cicatrices et brûlures', 'Eczéma sévère', 'Teint terne et sans éclat'], dosage: 'TRÈS concentré — utiliser 5 à 10% maximum (quelques gouttes) mélangé à une huile de base. Tache en orange.', precautions: 'Tache les vêtements et la peau (orange). Utiliser en très petite quantité diluée. Non comédogène.', origine: 'Mongolie, Chine, Russie', odeur: 'Caractéristique, légèrement rance', association: ['Argan HV', 'Rose musquée HV', 'Vitamine E'], tags: ['anti-âge', 'régénérant', 'cicatrices', 'eczéma', 'éclat', 'puissant'] },

  { id: 'hv_argan', nom: 'Argan', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Anti-âge exceptionnel', 'Régénérant cutané', 'Nourrissante sans effet gras', 'Fortifiante cheveux', 'Antioxydante'], utilisations: ['Soins anti-âge visage', 'Cheveux secs et abîmés', 'Ongles fragiles', 'Soin nuit régénérant'], dosage: '3 à 5 gouttes pour le visage. Quelques gouttes sur cheveux secs.', precautions: 'Excellente tolérance.', origine: 'Maroc (Souss)', odeur: 'Légèrement toastée', association: ['Rose de Damas HE', 'Néroli HE', 'Vitamine E'], tags: ['anti-rides', 'peau mature', 'cheveux', 'régénérant', 'antioxydant'] },

  { id: 'hv_avocat', nom: 'Avocat', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Très nourrissante et riche', 'Pénètre en profondeur', 'Idéale peaux très sèches', 'Fortifiante capillaire', 'Riche en vitamines A, D, E'], utilisations: ['Peaux très sèches', 'Masques capillaires profonds', 'Peaux matures', 'Corps en hiver'], dosage: 'Mélanger 30% avocat + 70% huile plus légère pour visage.', precautions: 'Très riche — mélanger. Peut être lourde pour peaux grasses.', origine: 'Mexique, Afrique du Sud, Espagne', odeur: 'Légèrement végétale', association: ['Jojoba', 'Amande douce', 'Vitamine E'], tags: ['peau sèche', 'cheveux', 'nourrissant', 'hiver', 'vitamines'] },

  { id: 'hv_baobab', nom: 'Baobab', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Ultra-nourrissante', 'Élastifiante et repulpante', 'Anti-âge', 'Régénérante', 'Riche en omégas 3-6-9'], utilisations: ['Peaux matures et déshydratées', 'Vergetures', 'Cheveux très secs', 'Anti-âge corporel'], dosage: '3 à 5 gouttes sur visage ou cheveux. Pure ou mélangée.', precautions: 'Excellente tolérance. Légèrement plus lourde que jojoba.', origine: 'Afrique subsaharienne', odeur: 'Légèrement noix, douce', association: ['Argan HV', 'Rose musquée HV', 'Néroli HE'], tags: ['anti-âge', 'nourrissant', 'vergetures', 'cheveux', 'omégas'] },

  { id: 'hv_bourrache', nom: 'Bourrache', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Riche en GLA (acide gamma-linolénique)', 'Anti-inflammatoire', 'Régulateur hormonal', 'Régénérant cutané', 'Idéale peaux atopiques'], utilisations: ['Eczéma et psoriasis', 'Soins ménopause', 'Rosacée', 'Peaux très sèches et atopiques', 'Anti-âge'], dosage: 'Utiliser 10 à 20% dans une formulation. 2 à 3 gouttes pures sur zone ciblée.', precautions: 'Conserver au réfrigérateur. S\'oxyde rapidement. Ajouter vitamine E comme conservateur.', origine: 'France, Italie, Espagne', odeur: 'Légèrement végétale, herbacée', association: ['Onagre HV', 'Rose musquée HV', 'Vitamine E'], tags: ['eczéma', 'psoriasis', 'ménopause', 'atopique', 'anti-inflammatoire'] },

  { id: 'hv_calendula', nom: 'Calendula (souci)', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Anti-inflammatoire puissant', 'Cicatrisante', 'Apaisante', 'Idéale peaux fragiles et irritées', 'Protectrice'], utilisations: ['Peaux irritées et rouges', 'Cicatrices récentes', 'Couperose', 'Eczéma', 'Bébé', 'Érythème fessier'], dosage: 'Utiliser pure ou mélangée 50/50 avec amande douce.', precautions: 'Allergie aux astéracées possible. Sinon très bien tolérée.', origine: 'France, Europe', odeur: 'Herbacée, légèrement amère', association: ['Camomille romaine HE', 'Lavande HE'], tags: ['cicatrisant', 'irritation', 'couperose', 'bébé', 'eczéma', 'apaisant'] },

  { id: 'hv_carotte', nom: 'Carotte (macérât)', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Stimulant de la pigmentation', 'Anti-âge et régénérant', 'Drainant', 'Éclat du teint', 'Riche en bêta-carotène'], utilisations: ['Préparation au bronzage naturel', 'Teint terne et sans éclat', 'Peaux matures', 'Anti-taches'], dosage: 'Utiliser 10 à 20% dans formulation. Colore légèrement la peau en orangé.', precautions: 'Colore légèrement la peau. À associer à une huile de base. Non photosensibilisant.', origine: 'France, Italie', odeur: 'Légèrement végétale, douce', association: ['Argan HV', 'Jojoba HV', 'Géranium HE'], tags: ['bronzage', 'teint', 'éclat', 'anti-âge', 'anti-taches'] },

  { id: 'hv_chanvre', nom: 'Chanvre', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Anti-inflammatoire puissant', 'Riche en omégas 3-6 équilibrés', 'Régulateur sébacé', 'Idéale peaux sensibles et acnéiques'], utilisations: ['Acné inflammatoire', 'Eczéma', 'Peaux sensibles et réactives', 'Couperose'], dosage: '2 à 5 gouttes pures pour visage. Mélanger avec jojoba pour peaux grasses.', precautions: 'S\'oxyde rapidement — conserver au réfrigérateur. Ajouter vitamine E.', origine: 'France, Canada, Chine', odeur: 'Légèrement végétale, noix', association: ['Tea Tree HE', 'Lavande HE', 'Vitamine E'], tags: ['acné', 'eczéma', 'anti-inflammatoire', 'peau sensible', 'couperose'] },

  { id: 'hv_coco', nom: 'Coco (noix de coco) fractionné', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Légère et pénétrante', 'Antibactérienne légère', 'Stable et longue conservation', 'Bonne base de massage'], utilisations: ['Base de massage légère', 'Démaquillage', 'Corps', 'Cheveux fins'], dosage: 'Utiliser pure. Reste liquide à toutes températures contrairement au beurre de coco.', precautions: 'Différent du beurre de coco. Plus légère et non comédogène.', origine: 'Philippines, Indonésie, Malaisie', odeur: 'Très légère, subtile', association: ['Toutes HE', 'Ylang-ylang HE'], tags: ['légère', 'massage', 'stable', 'cheveux fins', 'démaquillage'] },

  { id: 'hv_framboise', nom: 'Pépin de framboise', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Protection UV naturelle (SPF 28-50 estimé)', 'Anti-oxydante', 'Anti-inflammatoire', 'Régénérante', 'Nourrissante légère'], utilisations: ['Soins solaires naturels (complémentaire)', 'Anti-âge', 'Peaux atopiques', 'Après-soleil'], dosage: '5 à 20% dans vos formulations. Pas seule comme crème solaire — complément uniquement.', precautions: 'Ne remplace PAS une vraie protection solaire. Utiliser en complément uniquement.', origine: 'Canada, USA, Europe de l\'Est', odeur: 'Légèrement fruitée, douce', association: ['Calendula HV', 'Vitamine E', 'Zinc'], tags: ['UV', 'solaire', 'antioxydant', 'anti-inflammatoire', 'après-soleil'] },

  { id: 'hv_jojoba', nom: 'Jojoba', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Régulateur du sébum unique', 'Non comédogène', 'Légère et non grasse', 'Mimique du sébum naturel', 'Stabilisante'], utilisations: ['Peaux grasses et mixtes', 'Acné', 'Cuir chevelu gras', 'Démaquillant naturel', 'Base légère'], dosage: 'Peut s\'utiliser pure à 100%.', precautions: 'Techniquement une cire liquide. Excellente tolérance. Très stable — longue conservation.', origine: 'Mexique, Pérou, Israël', odeur: 'Pratiquement inodore', association: ['Tea Tree HE', 'Citron HE', 'Ylang-ylang HE'], tags: ['peau grasse', 'acné', 'sébum', 'légère', 'démaquillant', 'stable'] },

  { id: 'hv_macadamia', nom: 'Macadamia', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Nourrissante et réparatrice', 'Riche en acide palmitoléique (mimique peau âgée)', 'Anti-âge', 'Émolliente douce'], utilisations: ['Peaux matures et âgées', 'Corps et mains', 'Cheveux fragiles', 'Ongles'], dosage: '3 à 5 gouttes pour le visage. Pure sur corps.', precautions: 'Allergie aux fruits à coque possible. Très bien tolérée sinon.', origine: 'Australie, Hawaii, Afrique du Sud', odeur: 'Légère, noix douce', association: ['Argan HV', 'Rose musquée HV', 'Encens HE'], tags: ['peau mature', 'anti-âge', 'nourrissant', 'cheveux', 'mains'] },

  { id: 'hv_millepertuis', nom: 'Millepertuis', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Anti-inflammatoire cutané', 'Cicatrisant neuro-musculaire', 'Antalgique local', 'Anti-brûlures solaires'], utilisations: ['Brûlures légères et coups de soleil', 'Douleurs nerveuses', 'Névrites', 'Herpès labial'], dosage: 'Appliquer pur sur zone concernée. Ne pas utiliser en grande quantité.', precautions: 'PHOTOSENSIBILISANT MAJEUR — jamais avant exposition solaire. Interactions médicamenteuses nombreuses.', origine: 'France, Europe', odeur: 'Rouge-orangée caractéristique, herbacée', association: ['Lavande HE', 'Camomille HE'], tags: ['brûlures', 'soleil', 'douleurs nerveuses', 'herpès', 'photosensibilisant'] },

  { id: 'hv_nigelle', nom: 'Nigelle (cumin noir)', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Anti-allergique naturel', 'Anti-inflammatoire', 'Immunostimulante', 'Rééquilibrante cutanée', 'Antifongique'], utilisations: ['Eczéma et psoriasis', 'Allergies cutanées', 'Acné inflammatoire', 'Renforcement immunitaire'], dosage: '2 à 5 gouttes pures sur les zones concernées.', precautions: 'Odeur forte et caractéristique. Tester avant usage étendu.', origine: 'Égypte, Syrie, Éthiopie', odeur: 'Épicée, poivrée, caractéristique', association: ['Lavande HE', 'Camomille HE'], tags: ['eczéma', 'allergie', 'acné', 'anti-inflammatoire', 'immunité'] },

  { id: 'hv_olive', nom: 'Olive vierge extra', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Protectrice et nourrissante', 'Antioxydante', 'Émolliente profonde', 'Anti-inflammatoire légère'], utilisations: ['Soins du corps', 'Masques capillaires', 'Soins très secs', 'Cuisine et usage interne'], dosage: 'Pure ou mélangée. Peut être lourde pour visage — préférer en base 30%.', precautions: 'Peut être comédogène pour peaux acnéiques. Odeur prononcée.', origine: 'Bassin méditerranéen', odeur: 'Olive caractéristique, végétale', association: ['Lavande HE', 'Romarin HE'], tags: ['corps', 'cheveux', 'antioxydant', 'nourrissant', 'masque'] },

  { id: 'hv_onagre', nom: 'Onagre (evening primrose)', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Régulateur hormonal féminin', 'Anti-inflammatoire puissant', 'Régénérant cutané', 'Idéale ménopause', 'SPM'], utilisations: ['Syndrome prémenstruel', 'Péri-ménopause et bouffées de chaleur', 'Eczéma', 'Psoriasis', 'Peaux matures'], dosage: 'Utiliser 20 à 30% dans formulation ou 3 à 5 gouttes pures.', precautions: 'S\'oxyde rapidement — conserver au réfrigérateur. Ajouter vitamine E.', origine: 'Canada, USA, France', odeur: 'Légèrement végétale', association: ['Bourrache HV', 'Géranium HE', 'Vitamine E'], tags: ['hormones', 'ménopause', 'SPM', 'eczéma', 'régénérant'] },

  { id: 'hv_passiflore', nom: 'Passiflore', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Légère et non grasse', 'Astringente douce', 'Régulateur du sébum', 'Illuminatrice', 'Antioxydante'], utilisations: ['Peaux grasses et mixtes', 'Pores dilatés', 'Teint terne', 'Sérums légers'], dosage: '3 à 5 gouttes pures. Idéale en sérum légère ou mélange avec jojoba.', precautions: 'Excellente tolérance. Convient aux peaux à tendance acnéique.', origine: 'Amérique du Sud, Inde', odeur: 'Légèrement végétale, subtile', association: ['Tea Tree HE', 'Citron HE', 'Géranium HE'], tags: ['peau grasse', 'pores', 'éclat', 'légère', 'sébum'] },

  { id: 'hv_pepin_raisin', nom: 'Pépin de raisin', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Légère et non grasse', 'Astringente', 'Antioxydante (resvératrol)', 'Tonifiante', 'Équilibrante'], utilisations: ['Peaux grasses et mixtes', 'Massage', 'Base légère DIY', 'Soins corps légers'], dosage: 'Utiliser pure ou en base.', precautions: 'Peut contenir des résidus de pesticides — choisir bio. Excellente tolérance sinon.', origine: 'France, Italie, Espagne', odeur: 'Pratiquement inodore, neutre', association: ['Tea Tree HE', 'Citron HE', 'Géranium HE'], tags: ['peau grasse', 'légère', 'antioxydant', 'massage', 'équilibrante'] },

  { id: 'hv_ricin', nom: 'Ricin', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Stimulante de la pousse des cheveux', 'Fortifiant', 'Épaississante', 'Hydratante intense', 'Cicatrisante lèvres'], utilisations: ['Pousse des cheveux et cils', 'Cheveux très secs', 'Ongles cassants', 'Sourcils clairsemés', 'Lèvres gercées'], dosage: 'Appliquer pur sur cuir chevelu avant shampoing. Très épaisse — mélanger avec amande douce.', precautions: 'Très visqueuse. Mélanger avec huile légère pour application facile.', origine: 'Inde, Brésil, Éthiopie', odeur: 'Légèrement âcre', association: ['Romarin HE', 'Cèdre HE', 'Amande douce HV'], tags: ['cheveux', 'pousse', 'cils', 'sourcils', 'fortifiant', 'lèvres'] },

  { id: 'hv_rose_musquee', nom: 'Rose musquée', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Régénérante exceptionnelle', 'Anti-cicatrices et vergetures', 'Anti-rides', 'Riche en acides gras essentiels', 'Illuminatrice'], utilisations: ['Cicatrices et vergetures', 'Peaux matures', 'Anti-âge intensif', 'Taches et irrégularités de teint', 'Après-soleil'], dosage: '2 à 3 gouttes pures pour le visage le soir. Mélanger avec argan pour usage quotidien.', precautions: 'Peut être comédogène pour peaux très acnéiques. Conserver au frais.', origine: 'Chili, Pérou, Afrique du Sud', odeur: 'Légèrement végétale, subtile', association: ['Rose de Damas HE', 'Néroli HE', 'Vitamine E'], tags: ['cicatrices', 'vergetures', 'anti-rides', 'régénérant', 'taches', 'éclat'] },

  { id: 'hv_tamanu', nom: 'Tamanu (calophylle)', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Cicatrisante exceptionnelle', 'Anti-infectieux', 'Calmant les douleurs', 'Veineuse et drainante', 'Anti-neuropathique'], utilisations: ['Cicatrices profondes', 'Acné sévère', 'Problèmes veineux', 'Douleurs articulaires', 'Névralgies'], dosage: 'Utiliser pur sur petites zones ou mélanger 20% dans huile de base.', precautions: 'Allergie possible. Odeur puissante. Éviter grossesse par précaution.', origine: 'Polynésie, Mélanésie, Madagascar', odeur: 'Forte, verte, caractéristique', association: ['Tea Tree HE', 'Lavande HE', 'Rose musquée HV'], tags: ['cicatrices', 'acné', 'veines', 'douleurs', 'névralgies'] },


  { id: 'hv_noisette', nom: 'Noisette', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Régulateur du sébum', 'Pénétrante et non grasse', 'Idéale peaux mixtes à grasses', 'Astringente douce', 'Riche en vitamine E'], utilisations: ['Peaux mixtes et grasses', 'Acné', 'Pores dilatés', 'Démaquillage huileux', 'Cheveux gras'], dosage: 'Utiliser pure ou en base. Convient pour usage quotidien visage.', precautions: 'Allergie aux fruits à coque possible. Excellente tolérance sinon.', origine: 'France, Italie, Turquie', odeur: 'Noisette douce, agréable', association: ['Jojoba HV', 'Tea Tree HE', 'Géranium HE'], tags: ['peau grasse', 'sébum', 'acné', 'pores', 'pénétrante'] },

  { id: 'hv_noyau_abricot', nom: 'Noyau d\'abricot', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Adoucissante et nourrissante', 'Illuminatrice de teint', 'Bonne pénétration', 'Riche en vitamines A et E', 'Tonifiante'], utilisations: ['Peaux ternes et fatiguées', 'Soin visage anti-âge', 'Démaquillage', 'Peaux sensibles'], dosage: 'Utiliser pure ou en base. 3 à 5 gouttes pour visage.', precautions: 'Excellente tolérance. Idéale pour peaux ternes.', origine: 'France, Espagne, Italie', odeur: 'Légère, fruitée, douce', association: ['Carotte HV', 'Géranium HE', 'Néroli HE'], tags: ['éclat', 'teint', 'anti-âge', 'démaquillage', 'peau sensible'] },

  { id: 'hv_coco_vierge', nom: 'Coco vierge (huile pure)', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Nourrissante intense', 'Antibactérienne', 'Cheveux brillants et nourris', 'Hydrate les peaux très sèches', 'Saponifie facilement'], utilisations: ['Masques cheveux nourrissants', 'Démaquillage', 'Corps très sec', 'Lèvres', 'Savonnerie maison'], dosage: 'Solide en dessous de 24°C — fait fondre dans la main. Pure ou mélangée.', precautions: 'Comédogène pour visage acnéique — éviter. Différente de la coco fractionnée (toujours liquide).', origine: 'Philippines, Indonésie, Sri Lanka', odeur: 'Coco caractéristique, sucrée', association: ['Ylang-ylang HE', 'Citron HE', 'Argan HV'], tags: ['cheveux', 'nourrissant', 'masque', 'savon', 'lèvres'] },

  { id: 'hv_vanille', nom: 'Vanille (macérât)', type: 'Huile végétale', categorie: 'HV', bienfaits: ['Adoucissante et apaisante', 'Réconfortante (psyché)', 'Antioxydante douce', 'Parfum naturel sucré', 'Tonifiante peaux ternes'], utilisations: ['Soins peaux sensibles', 'Massages détente', 'Parfum naturel', 'Soin lèvres'], dosage: 'Utiliser pure ou en base. Idéal en soin du soir.', precautions: 'Macérât huileux (huile + extrait de gousses). Excellente tolérance.', origine: 'Madagascar, Tahiti, La Réunion', odeur: 'Vanille intense, sucrée, gourmande', association: ['Beurre de karité', 'Argan HV', 'Néroli HE'], tags: ['douceur', 'parfum', 'peau sensible', 'massage', 'apaisant'] },

  // ══════════════════════════════════════════════════════════════════════════
  // BEURRES VÉGÉTAUX
  // ══════════════════════════════════════════════════════════════════════════

  { id: 'beurre_karite', nom: 'Karité', type: 'Beurre végétal', categorie: 'Beurre', bienfaits: ['Ultra-nourrissant', 'Protecteur et émollient', 'Cicatrisant', 'Anti-UV léger SPF 6', 'Régénérant'], utilisations: ['Peaux très sèches et abîmées', 'Lèvres gercées', 'Masques capillaires profonds', 'Corps et mains', 'Bébé', 'Coudes et talons'], dosage: 'Utiliser pur ou fondu au bain-marie. Mélanger avec huile légère pour texture fluide.', precautions: 'Peut être lourd pour peaux grasses ou acnéiques. Allergie rare aux beurres.', origine: 'Afrique de l\'Ouest (Sahel)', odeur: 'Légèrement noix, caractéristique', association: ['Lavande HE', 'Géranium HE', 'Avocat HV'], tags: ['peau très sèche', 'cheveux', 'lèvres', 'nourrissant', 'bébé', 'talons'] },

  { id: 'beurre_cacao', nom: 'Cacao', type: 'Beurre végétal', categorie: 'Beurre', bienfaits: ['Anti-vergetures', 'Émollient profond', 'Antioxydant', 'Protecteur cutané', 'Raffermissant'], utilisations: ['Prévention et soin des vergetures', 'Corps très sec', 'Lèvres', 'Crèmes maison', 'Grossesse'], dosage: 'Fondre légèrement avant utilisation. Mélanger avec karité ou huile végétale.', precautions: 'Peut être lourd. Allergie chocolat/cacao possible.', origine: 'Côte d\'Ivoire, Ghana, Équateur', odeur: 'Chocolat, douce, caractéristique', association: ['Rose musquée HV', 'Géranium HE', 'Néroli HE'], tags: ['vergetures', 'corps', 'lèvres', 'antioxydant', 'grossesse'] },

  { id: 'beurre_coco', nom: 'Coco (noix de coco)', type: 'Beurre végétal', categorie: 'Beurre', bienfaits: ['Antibactérien naturel', 'Nourrissant cheveux', 'Démaquillant', 'Lèvres et corps', 'Fond facilement'], utilisations: ['Masques cheveux brillance', 'Démaquillage', 'Corps et lèvres', 'Pointes sèches'], dosage: 'Fond à 24°C. Éviter sur visage si peau acnéique.', precautions: 'Comédogène pour certaines peaux — éviter si acné sévère.', origine: 'Philippines, Indonésie, Thaïlande', odeur: 'Noix de coco caractéristique', association: ['Ylang-ylang HE', 'Citron HE'], tags: ['cheveux', 'brillance', 'démaquillant', 'lèvres', 'corps'] },

  { id: 'beurre_illipe', nom: 'Illipé', type: 'Beurre végétal', categorie: 'Beurre', bienfaits: ['Régénérant et restructurant', 'Raffermissant cutané', 'Excellent pour les cheveux abîmés', 'Très proche du karité'], utilisations: ['Cheveux abîmés et poreux', 'Corps secs', 'Produits capillaires de luxe', 'Peaux matures'], dosage: 'Fondre au bain-marie. Utiliser seul ou mélangé avec autres beurres.', precautions: 'Moins connu — tester avant usage étendu. Excellente tolérance généralement.', origine: 'Indonésie, Malaisie, Bornéo', odeur: 'Neutre à légèrement végétale', association: ['Argan HV', 'Ylang-ylang HE'], tags: ['cheveux abîmés', 'restructurant', 'raffermissant', 'luxe', 'corps'] },

  { id: 'beurre_mangue', nom: 'Mangue', type: 'Beurre végétal', categorie: 'Beurre', bienfaits: ['Protecteur et régénérant', 'Texture légère pour un beurre', 'Riche en vitamines A et E', 'Émollient doux', 'Antiparasitaire'], utilisations: ['Corps et peaux sèches', 'Après-soleil', 'Cheveux fins', 'Lèvres', 'Produits solaires naturels'], dosage: 'Peut s\'utiliser pur ou mélangé. Plus léger que karité.', precautions: 'Allergie mangue possible. Excellente tolérance sinon.', origine: 'Inde, Afrique de l\'Ouest', odeur: 'Légèrement fruitée, douce', association: ['Palmarosa HE', 'Géranium HE', 'Jojoba HV'], tags: ['corps', 'après-soleil', 'vitamines', 'léger', 'cheveux fins', 'solaire'] },

  { id: 'beurre_murumuru', nom: 'Murumuru', type: 'Beurre végétal', categorie: 'Beurre', bienfaits: ['Hydratant intense', 'Définisseur de boucles naturel', 'Anti-frisottis', 'Brillance capillaire'], utilisations: ['Cheveux bouclés et frisés', 'Définition des boucles', 'Anti-humidité pour cheveux', 'Soins naturels afro'], dosage: 'Fondre légèrement. Appliquer sur cheveux humides ou secs pour styler.', precautions: 'Peut être lourd sur cheveux fins. Idéal pour cheveux épais et bouclés.', origine: 'Amazonie brésilienne', odeur: 'Légèrement végétale, subtile', association: ['Ylang-ylang HE', 'Ricin HV', 'Huile de coco'], tags: ['boucles', 'frisottis', 'afro', 'définition', 'brillance', 'humidité'] },

  { id: 'beurre_shorea', nom: 'Shorea (sal butter)', type: 'Beurre végétal', categorie: 'Beurre', bienfaits: ['Alternative naturelle au karité', 'Nourrissant et protecteur', 'Antirides léger', 'Bonne pénétration'], utilisations: ['Peaux sèches', 'Produits lèvres', 'Corps', 'Cheveux'], dosage: 'Utiliser comme le karité. Texture légèrement plus dure.', precautions: 'Peu connu — tester. Excellente tolérance généralement.', origine: 'Inde, Asie du Sud-Est', odeur: 'Légère, noix douce', association: ['Lavande HE', 'Argan HV'], tags: ['peau sèche', 'lèvres', 'corps', 'nourrissant', 'alternative karité'] },

  // ══════════════════════════════════════════════════════════════════════════
  // HYDROLATS (A–Z)
  // ══════════════════════════════════════════════════════════════════════════

  { id: 'hydrolat_bleuet', nom: 'Bleuet', type: 'Hydrolat', categorie: 'Hydrolat', bienfaits: ['Décongestionnant oculaire', 'Apaisant pour yeux fatigués', 'Anti-inflammatoire', 'Tonifiant doux'], utilisations: ['Compresses pour yeux rouges et fatigués', 'Cernes et poches', 'Conjonctivite légère', 'Tonique visage doux'], dosage: 'Compresse 10 minutes sur les yeux. Pulvériser sur visage ou appliquer sur coton.', precautions: 'Excellente tolérance. Convient aux peaux très sensibles et aux yeux.', origine: 'France', odeur: 'Légère, florale, bleuet', association: ['Rose HE', 'Camomille HE'], tags: ['yeux', 'cernes', 'poches', 'apaisant', 'tonique', 'sensible'] },

  { id: 'hydrolat_camomille', nom: 'Camomille romaine', type: 'Hydrolat', categorie: 'Hydrolat', bienfaits: ['Apaisant intense', 'Anti-allergique', 'Idéal bébé et peaux très sensibles', 'Calmant yeux'], utilisations: ['Peaux ultra-sensibles', 'Yeux fatigués et irrités', 'Bébé', 'Eczéma', 'Couperose'], dosage: 'Pulvériser directement. Compresse sur les yeux 10 minutes.', precautions: 'Allergie aux astéracées possible mais rare.', origine: 'France, Grande-Bretagne', odeur: 'Douce, pomme, délicate', association: ['Camomille HE', 'Calendula HV'], tags: ['peau sensible', 'allergies', 'yeux', 'bébé', 'eczéma', 'couperose'] },

  { id: 'hydrolat_cypres', nom: 'Cyprès toujours vert', type: 'Hydrolat', categorie: 'Hydrolat', bienfaits: ['Déodorant naturel', 'Anti-transpiration', 'Veineux et drainant', 'Tonifiant'], utilisations: ['Déodorant naturel', 'Jambes lourdes', 'Transpiration excessive', 'Drainage'], dosage: 'Pulvériser directement sur zones concernées.', precautions: 'Éviter pendant grossesse et si cancer hormono-dépendant.', origine: 'France', odeur: 'Boisée, fraîche, résineuse', association: ['Cyprès HE', 'Hamamélis HYD'], tags: ['déodorant', 'transpiration', 'jambes', 'drainage', 'tonifiant'] },

  { id: 'hydrolat_geranium', nom: 'Géranium rosat', type: 'Hydrolat', categorie: 'Hydrolat', bienfaits: ['Équilibrant et tonifiant', 'Régulateur du sébum', 'Anti-inflammatoire doux', 'Hémostatique léger'], utilisations: ['Tonique universel pour tous types de peaux', 'Peaux mixtes', 'Petites coupures', 'Après épilation'], dosage: 'Pulvériser directement sur visage propre ou appliquer sur coton.', precautions: 'Excellente tolérance. Éviter en grande quantité pendant grossesse.', origine: 'Égypte, Maroc', odeur: 'Florale, légèrement rosée', association: ['Géranium HE', 'Jojoba HV'], tags: ['tous types de peaux', 'sébum', 'épilation', 'tonique', 'équilibrant'] },

  { id: 'hydrolat_hamamélis', nom: 'Hamamélis', type: 'Hydrolat', categorie: 'Hydrolat', bienfaits: ['Astringent et tonifiant', 'Resserrant des pores', 'Anti-inflammatoire', 'Veineux et décongestionnant'], utilisations: ['Peaux grasses et mixtes', 'Pores dilatés', 'Jambes lourdes', 'Yeux gonflés', 'Après rasage'], dosage: 'Appliquer sur coton ou pulvériser directement sur peau nette.', precautions: 'Déconseillé en cas de peau très sèche ou sensible.', origine: 'Canada, États-Unis', odeur: 'Légèrement tannique, délicate', association: ['Géranium HE', 'Citron HE'], tags: ['peau grasse', 'pores', 'astringent', 'jambes', 'rasage'] },

  { id: 'hydrolat_helichryse', nom: 'Hélichryse italienne', type: 'Hydrolat', categorie: 'Hydrolat', bienfaits: ['Anti-hématomes exceptionnel', 'Anti-inflammatoire', 'Cicatrisant', 'Anti-âge', 'Drainant'], utilisations: ['Coups et hématomes', 'Cicatrices', 'Couperose', 'Soins anti-âge intensifs', 'Yeux cernés'], dosage: 'Appliquer directement ou sur compresse. Peut remplacer l\'eau dans les recettes de soins.', precautions: 'Excellente tolérance. L\'un des hydrolats les mieux supportés.', origine: 'France, Corse, Balkans', odeur: 'Douce, miel, légèrement épicée', association: ['Hélichryse HE', 'Rose musquée HV', 'Argan HV'], tags: ['hématomes', 'cicatrices', 'couperose', 'anti-âge', 'cernes'] },

  { id: 'hydrolat_lavande', nom: 'Lavande vraie', type: 'Hydrolat', categorie: 'Hydrolat', bienfaits: ['Apaisant et cicatrisant', 'Antiseptique doux', 'Hydratant', 'Réducteur de rougeurs', 'Multi-usage'], utilisations: ['Tonique peaux sensibles et acnéiques', 'Après-rasage', 'Coups de soleil', 'Piqûres'], dosage: 'Pulvériser directement. Peut être ingéré (1 c. à café dans eau).', precautions: 'Déconseillé femme enceinte par prudence en ingestion.', origine: 'France (Provence)', odeur: 'Florale, herbacée, lavande douce', association: ['Lavande HE', 'Camomille HE'], tags: ['apaisant', 'acné', 'coups de soleil', 'cicatrisant', 'multi-usage'] },

  { id: 'hydrolat_menthe', nom: 'Menthe poivrée', type: 'Hydrolat', categorie: 'Hydrolat', bienfaits: ['Rafraîchissant puissant', 'Décongestionnant nasal', 'Tonifiant', 'Anti-démangeaisons', 'Digestif'], utilisations: ['Brume fraîcheur été', 'Jambes lourdes', 'Démangeaisons cutanées', 'Coup de chaud', 'Aérosol nasal léger'], dosage: 'Pulvériser directement. Ne jamais ingérer pur.', precautions: 'Ne jamais utiliser sur bébé ou enfant de moins de 7 ans. Déconseillé grossesse.', origine: 'France, Maroc', odeur: 'Fraîche, mentholée, puissante', association: ['Hamamélis HYD', 'Lavande HYD'], tags: ['fraîcheur', 'été', 'jambes', 'démangeaisons', 'nez', 'digestif'] },

  { id: 'hydrolat_romarin', nom: 'Romarin à cinéole', type: 'Hydrolat', categorie: 'Hydrolat', bienfaits: ['Stimulant capillaire', 'Drainant hepatique', 'Tonifiant', 'Stimulant de la mémoire'], utilisations: ['Rinçage final capillaire pour brillance', 'Soins cuir chevelu gras', 'Lotion tonique corps', 'Drainage'], dosage: 'Utiliser en rinçage ou pulvériser directement sur cuir chevelu.', precautions: 'Déconseillé grossesse, hypertension, épilepsie.', origine: 'France, Espagne, Maroc', odeur: 'Fraîche, camphrée, herbacée', association: ['Romarin HE', 'Cyprès HYD'], tags: ['cheveux', 'brillance', 'cuir chevelu', 'drainage', 'mémoire'] },

  { id: 'hydrolat_rose', nom: 'Rose de Damas', type: 'Hydrolat', categorie: 'Hydrolat', bienfaits: ['Tonique et hydratant', 'Anti-rides et raffermissant', 'Apaisant peaux sensibles', 'Régulateur du pH cutané', 'Aphrodisiaque léger'], utilisations: ['Tonique visage matin et soir', 'Brume hydratante', 'Base soins DIY', 'Yeux gonflés et fatigués', 'Parfum naturel'], dosage: 'Pulvériser directement sur visage propre ou sur coton.', precautions: 'Conserver au réfrigérateur après ouverture. Durée 1 an.', origine: 'Bulgarie, Maroc, Iran', odeur: 'Rosée, florale, délicate', association: ['Rose de Damas HE', 'Argan HV', 'Aloe vera'], tags: ['tonique', 'hydratant', 'anti-rides', 'peau sensible', 'brume', 'parfum'] },

  { id: 'hydrolat_thym', nom: 'Thym à linalol', type: 'Hydrolat', categorie: 'Hydrolat', bienfaits: ['Purifiante et tonifiante', 'Légèrement antibactérien', 'Drainant lymphatique', 'Stimulant immunitaire'], utilisations: ['Soins peaux à imperfections', 'Lotion purifiante', 'Prévention infections cutanées', 'Drainage corps'], dosage: 'Pulvériser directement sur visage ou appliquer sur coton.', precautions: 'Forme linalol : la plus douce. Éviter grandes quantités pendant grossesse.', origine: 'France (Provence)', odeur: 'Herbacée, légèrement fleurie, thym doux', association: ['Tea Tree HE', 'Lavande HYD'], tags: ['purifiant', 'imperfections', 'drainage', 'immunité', 'tonifiant'] },

  // ══════════════════════════════════════════════════════════════════════════
  // ACTIFS NATURELS ET INGRÉDIENTS DIY
  // ══════════════════════════════════════════════════════════════════════════

  { id: 'acide_azelaic', nom: 'Acide azélaïque', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Anti-hyperpigmentation', 'Anti-acné doux', 'Anti-rosacée', 'Antibactérien cutané', 'Antioxydant'], utilisations: ['Taches de vieillesse', 'Acné et comédons', 'Rosacée', 'Mélasma'], dosage: '5 à 20% dans vos formulations. Démarrer par 5% pour tester la tolérance.', precautions: 'Peut irriter légèrement au début. Éviter contour des yeux. Déconseillé grossesse à forte dose.', origine: 'Dérivé naturel des céréales (blé, orge)', odeur: 'Inodore', association: ['Niacinamide', 'Aloe vera', 'Hydrolat rose'], tags: ['taches', 'acné', 'rosacée', 'mélasma', 'hyperpigmentation'] },

  { id: 'acide_hyaluronique', nom: 'Acide hyaluronique', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Hydratation extrême', 'Repulpant anti-rides', 'Effet lissant immédiat', 'Favorise régénération cellulaire', 'Multi-poids moléculaires'], utilisations: ['Sérums hydratants', 'Anti-rides', 'Peaux déshydratées', 'Boosters DIY'], dosage: '0.1 à 2% dans vos préparations selon le grade moléculaire. Dissoudre dans eau. Appliquer sur peau humide.', precautions: 'Appliquer sur peau humide pour maximiser effet. Très bonne tolérance.', origine: 'Fermentation végétale', odeur: 'Inodore', association: ['Aloe vera', 'Niacinamide', 'Hydrolats'], tags: ['hydratation', 'anti-rides', 'repulpant', 'sérum', 'déshydraté'] },

  { id: 'acide_lactique', nom: 'Acide lactique', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Exfoliant doux (AHA)', 'Hydratant', 'Lissant', 'Anti-taches doux', 'Illuminateur de teint'], utilisations: ['Peaux ternes', 'Pores dilatés', 'Gommage chimique doux', 'Taches légères'], dosage: '5 à 10% pour usage cosmétique (avec pH 3.5-4). Commencer à 5%.', precautions: 'Photosensibilisant — utiliser le soir. Éviter si peau très sensible ou irritée.', origine: 'Fermentation naturelle (lait, fruits)', odeur: 'Légèrement acide', association: ['Aloe vera', 'Niacinamide', 'Hydrolat rose'], tags: ['exfoliant', 'éclat', 'taches', 'pores', 'gommage chimique'] },

  { id: 'acide_salicylique', nom: 'Acide salicylique', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Exfoliant BHA kératolytique', 'Anti-acné', 'Désobstruant des pores', 'Anti-comédons'], utilisations: ['Acné', 'Points noirs', 'Pores dilatés', 'Exfoliation en profondeur'], dosage: '0.5 à 2% dans vos formulations cosmétiques.', precautions: 'Photosensibilisant. Éviter grossesse. Ne pas dépasser 2% en cosmétique.', origine: 'Dérivé naturel de l\'écorce de saule', odeur: 'Légèrement médicamenteux', association: ['Niacinamide', 'Tea Tree HE', 'Aloe vera'], tags: ['acné', 'pores', 'comédons', 'exfoliant', 'BHA'] },

  { id: 'aloe_vera', nom: 'Aloe vera (gel)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Hydratant intense', 'Cicatrisant', 'Apaisant brûlures', 'Anti-inflammatoire', 'Stimulant pousse cheveux', 'Soin solaire'], utilisations: ['Gel hydratant naturel', 'Après-soleil', 'Brûlures légères', 'Masques cheveux', 'Blessures légères', 'Acné'], dosage: 'Utiliser le gel pur directement sur la peau ou les cheveux. Peut être congelé en cubes.', precautions: 'Choisir gel 99-100% aloe vera sans alcool ni parfum. Allergie rare possible.', origine: 'Afrique, Caraïbes, Méditerranée', odeur: 'Pratiquement inodore', association: ['Lavande HE', 'Tea Tree HE', 'Calendula HV'], tags: ['hydratation', 'brûlures', 'soleil', 'cheveux', 'cicatrisant', 'acné'] },

  { id: 'argile_blanche', nom: 'Argile blanche (kaolin)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Douce et purifiante', 'Absorbante légère', 'Idéale peaux sensibles', 'Matifiante sans agresser', 'Détoxifiante légère'], utilisations: ['Masques peaux sensibles et mixtes', 'Déodorant naturel', 'Dentifrice maison', 'Poudres cosmétiques', 'Poudre libre'], dosage: 'Mélanger avec eau, lait végétal ou hydrolat pour masque doux.', precautions: 'La plus douce des argiles. Convient aux peaux sensibles.', origine: 'France, Chine', odeur: 'Neutre', association: ['Camomille romaine HE', 'Rose HE', 'Hydrolat rose'], tags: ['peau sensible', 'masque', 'doux', 'purifiant', 'déodorant', 'poudre'] },

  { id: 'argile_ghassoul', nom: 'Ghassoul (lava clay)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Nettoyant et purifiant doux', 'Riche en minéraux', 'Sébo-régulateur', 'Adoucissant', 'Idéal pour nettoyage sans savon'], utilisations: ['Masque purifiant pour tous types de peaux', 'Shampoing naturel (no-poo)', 'Corps et cheveux', 'Bain purifiant'], dosage: 'Mélanger avec eau ou hydrolat. Laisser poser 10-15 min. Rincer.', precautions: 'Naturel et très bien toléré. Peut assécher si trop fréquent.', origine: 'Maroc (Atlas)', odeur: 'Minérale, neutre, légèrement argile', association: ['Huile d\'argan', 'Hydrolat rose', 'Huile de ricin'], tags: ['purifiant', 'no-poo', 'cheveux', 'minéraux', 'shampoing naturel'] },

  { id: 'argile_rose', nom: 'Argile rose (kaolin rouge)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Mélange kaolin et rouge', 'Douce et purifiante', 'Équilibrante', 'Bonne pour peaux mixtes'], utilisations: ['Masques peaux normales à mixtes', 'Peaux sensibles qui tolèrent mal la verte', 'Corps et visage'], dosage: 'Mélanger avec eau, lait végétal ou hydrolat.', precautions: 'Intermédiaire entre blanche et rouge. Très bien tolérée.', origine: 'France, USA', odeur: 'Neutre minérale', association: ['Géranium HE', 'Hydrolat géranium'], tags: ['masque', 'peaux mixtes', 'équilibrante', 'douce', 'purifiante'] },

  { id: 'argile_rouge', nom: 'Argile rouge', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Reminéralisante', 'Stimulante circulatoire', 'Nourrissante', 'Tonifiante', 'Anti-couperose'], utilisations: ['Masques peaux sèches et matures', 'Corps', 'Cataplasmes circulatoires', 'Bains minéraux'], dosage: 'Mélanger avec eau, huile végétale ou hydrolat pour consistance crémeuse.', precautions: 'Déconseillée pour peaux grasses et acnéiques. Riche et nourrissante.', origine: 'France, Australie', odeur: 'Terreuse, minérale', association: ['Géranium HE', 'Rose musquée HV', 'Hydrolat rose'], tags: ['peau sèche', 'peau mature', 'circulatoire', 'minéraux', 'nourrissante'] },

  { id: 'argile_verte', nom: 'Argile verte', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Absorbante et purifiante', 'Désinfectante', 'Reminéralisante', 'Détoxifiante', 'La plus polyvalente'], utilisations: ['Masques peaux grasses et acnéiques', 'Soin cuir chevelu gras', 'Cataplasmes', 'Nettoyage en profondeur'], dosage: 'Mélanger avec eau, hydrolat ou aloe vera. Ne jamais utiliser d\'ustensile en métal.', precautions: 'Ne pas laisser sécher complètement sur le visage. Éviter peaux sèches.', origine: 'France (bassin sédimentaire)', odeur: 'Minérale, neutre', association: ['Tea Tree HE', 'Citron HE', 'Hydrolat lavande'], tags: ['peau grasse', 'acné', 'purifier', 'détox', 'cuir chevelu'] },

  { id: 'bicarbonate', nom: 'Bicarbonate de soude', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Déodorant naturel', 'Exfoliant très doux', 'Assainissant', 'Anti-odeurs'], utilisations: ['Déodorant naturel maison', 'Gommage corps doux', 'Soins bucco-dentaires', 'Bains relaxants'], dosage: 'Petite quantité pour déodorant (peut irriter). 2 à 3 cuillères pour bain alcalinisant.', precautions: 'Peut perturber le pH cutané acide. Peut irriter peaux sensibles. À utiliser avec parcimonie.', origine: 'Minéral naturel', odeur: 'Neutre', association: ['Lavande HE', 'Tea Tree HE'], tags: ['déodorant', 'gommage', 'bain', 'anti-odeurs', 'exfoliant'] },

  { id: 'cafe_vert', nom: 'Café vert (extrait)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Anti-cellulite et drainant', 'Tonifiant circulatoire', 'Antioxydant', 'Lipolytique', 'Stimulant du métabolisme cutané'], utilisations: ['Soins minceur et anti-cellulite', 'Gommages corporels', 'Sérums raffermissants', 'Massage drainant'], dosage: '3 à 5% dans vos préparations corps. Marc de café pour gommage direct.', precautions: 'Usage externe uniquement. Éviter sur peaux irritées.', origine: 'Éthiopie, Colombie, Brésil', odeur: 'Café doux, végétal', association: ['Cyprès HE', 'Cèdre HE', 'Menthe HE'], tags: ['cellulite', 'minceur', 'drainant', 'tonifiant', 'gommage'] },

  { id: 'cire_carnauba', nom: 'Cire de carnauba', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Structurante', 'Protectrice', 'Brillante', 'Végane (alternative cire d\'abeille)'], utilisations: ['Baumes à lèvres', 'Déodorants solides', 'Rouges à lèvres naturels', 'Produits cosmétiques solides'], dosage: '5 à 15% dans vos formulations solides selon la dureté souhaitée.', precautions: 'Excellente tolérance. Végane.', origine: 'Brésil (palmier carnauba)', odeur: 'Neutre', association: ['Beurre de karité', 'Huile de coco', 'Cire d\'abeille'], tags: ['baume', 'lèvres', 'déodorant', 'végane', 'cosmétique solide'] },

  { id: 'cire_abeille', nom: 'Cire d\'abeille', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Structurante et protectrice', 'Émolliente', 'Film protecteur naturel', 'Anti-bactérienne légère'], utilisations: ['Baumes à lèvres', 'Crèmes corps', 'Bougies', 'Onguents naturels', 'Produits capillaires pomade'], dosage: '5 à 20% dans vos formulations selon texture souhaitée.', precautions: 'Non végane. Tester en cas d\'allergie aux produits de la ruche.', origine: 'Monde entier (apiculture)', odeur: 'Miel, légèrement sucrée', association: ['Propolis', 'Miel', 'Huile de coco'], tags: ['baume', 'lèvres', 'protecteur', 'structurant', 'apiculture'] },

  { id: 'collagene_vegetal', nom: 'Collagène végétal (hydrolysé)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Repulpant anti-rides', 'Hydratant filmogène', 'Raffermissant', 'Lissant immédiat'], utilisations: ['Sérums anti-âge', 'Soins repulpants', 'Masques lifting'], dosage: '2 à 5% dans vos formulations.', precautions: 'Végétal (soja ou blé) — allergies possibles. Moins efficace que le collagène animal mais végane.', origine: 'Dérivé végétal (blé, soja, champignon)', odeur: 'Neutre', association: ['Acide hyaluronique', 'Vitamine C', 'Aloe vera'], tags: ['anti-rides', 'repulpant', 'raffermissant', 'sérum', 'lifting'] },

  { id: 'curcuma', nom: 'Curcuma (poudre)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Anti-inflammatoire puissant', 'Anti-oxydant', 'Éclaircissant naturel', 'Anti-acné', 'Protecteur cutané'], utilisations: ['Masques anti-acné', 'Soins anti-taches', 'Masques glow maison', 'Soins anti-âge DIY'], dosage: 'Petite quantité (1/4 c. à café) dans masque. Tache — rincer soigneusement.', precautions: 'Tache la peau et les vêtements en jaune. Tester sur petite zone. Peut irriter.', origine: 'Inde, Asie du Sud-Est', odeur: 'Épicée chaude, curcuma caractéristique', association: ['Miel', 'Aloe vera', 'Argile blanche'], tags: ['anti-inflammatoire', 'anti-taches', 'acné', 'masque', 'éclat'] },

  { id: 'extrait_pepin_pamplemousse', nom: 'Extrait de pépin de pamplemousse (EPP)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Conservateur naturel', 'Antibactérien', 'Antifongique', 'Antioxydant'], utilisations: ['Conservateur dans préparations DIY', 'Soin des cuticules', 'Désinfectant léger', 'Tonique purifiant'], dosage: '0.5 à 1% dans vos préparations cosmétiques comme conservateur.', precautions: 'Interactions médicamenteuses connues (comme le pamplemousse frais). Diluer toujours.', origine: 'Pamplemousse (Citrus paradisi)', odeur: 'Légèrement citronnée, amère', association: ['Aloe vera', 'Hydrolat lavande'], tags: ['conservateur', 'antibactérien', 'DIY', 'antifongique', 'antioxydant'] },

  { id: 'fucus', nom: 'Fucus (algue brune)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Anti-cellulite et minceur', 'Stimulant thyroïdien léger', 'Drainant', 'Reminéralisant', 'Raffermissant'], utilisations: ['Soins minceur', 'Wraps corps anti-cellulite', 'Gels raffermissants', 'Bains minéraux'], dosage: '3 à 5% dans formulations corps. Poudre pour masques et wraps.', precautions: 'Riche en iode — éviter si problème thyroïdien. Éviter grossesse.', origine: 'Atlantique, Bretagne, Irlande', odeur: 'Marine, algue caractéristique', association: ['Café vert', 'Cyprès HE', 'Cèdre HE'], tags: ['cellulite', 'minceur', 'drainant', 'algue', 'raffermissant'] },

  { id: 'glycerine', nom: 'Glycérine végétale', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Humectant puissant', 'Hydratant', 'Adoucissant', 'Filmogène', 'Viscosant'], utilisations: ['Agent hydratant dans toutes préparations', 'Savons glycérinés', 'Crèmes et lotions', 'Gels aloe vera'], dosage: '2 à 10% dans vos formulations. Plus de 10% peut être collant.', precautions: 'Peut attirer l\'humidité en sens inverse si air trop sec. Excellente tolérance.', origine: 'Sous-produit végétal (colza, palme bio, coco)', odeur: 'Inodore, légèrement sucrée', association: ['Aloe vera', 'Acide hyaluronique', 'Hydrolats'], tags: ['hydratant', 'humectant', 'base DIY', 'savon', 'adoucissant'] },

  { id: 'kaolin_raffiné', nom: 'Kaolin raffiné (cosmétique)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Absorbe excès de sébum', 'Poudre libre naturelle', 'Matifiant longue durée', 'Base maquillage'], utilisations: ['Poudre libre naturelle', 'Base pour maquillage DIY', 'Fond de teint', 'Poudre de bébé'], dosage: 'Utiliser pur comme poudre ou mélanger avec pigments.', precautions: 'Grade cosmétique — ne pas inhaler. Excellente tolérance cutanée.', origine: 'France, Chine', odeur: 'Neutre', association: ['Oxyde de zinc', 'Pigments naturels'], tags: ['maquillage', 'poudre', 'matifiant', 'sébum', 'base cosmétique'] },

  { id: 'lierre', nom: 'Lierre grimpant (extrait)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Anti-cellulite puissant', 'Drainant et décongestionnant', 'Raffermissant', 'Tonifiant cutané', 'Lipolytique'], utilisations: ['Soins minceur', 'Cellulite et peau d\'orange', 'Corps raffermissant', 'Wraps'], dosage: '2 à 3% dans vos préparations. Souvent associé au café vert.', precautions: 'Éviter sur peaux sensibles. Ne pas ingérer. Irritant cutané à haute dose.', origine: 'Europe', odeur: 'Végétale, légère', association: ['Café vert', 'Cyprès HE', 'Cèdre HE'], tags: ['cellulite', 'minceur', 'raffermissant', 'drainant', 'peau d\'orange'] },

  { id: 'miel', nom: 'Miel brut (manuka ou local)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Antibactérien naturel puissant', 'Cicatrisant', 'Hydratant hygroscopique', 'Exfoliant enzymatique doux', 'Apaisant'], utilisations: ['Masques visage purifiants', 'Cicatrisation petites plaies', 'Soins lèvres', 'Masques capillaires', 'Acné'], dosage: 'Appliquer pur ou mélanger avec argile, aloe vera. Laisser 15-20 min.', precautions: 'Allergie au miel possible. Sucré — rincer soigneusement. Non végane.', origine: 'Monde entier (apiculture locale préférable)', odeur: 'Miel, sucrée, florale', association: ['Cannelle', 'Curcuma', 'Argile blanche'], tags: ['antibactérien', 'acné', 'cicatrisant', 'masque', 'hydratant'] },

  { id: 'niacinamide', nom: 'Niacinamide (vitamine B3)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Anti-taches et uniformisant', 'Resserrant des pores', 'Anti-inflammatoire', 'Régulateur du sébum', 'Barrière cutanée'], utilisations: ['Taches de pigmentation', 'Pores dilatés', 'Peaux grasses et acnéiques', 'Sérums anti-âge'], dosage: '2 à 5% dans vos formulations. Commencer à 2% pour tester la tolérance.', precautions: 'Très bien toléré. Peut causer légère rougeur à forte dose. Éviter avec acide ascorbique pur.', origine: 'Fermentation naturelle ou synthèse végétale', odeur: 'Légèrement acide', association: ['Acide hyaluronique', 'Zinc', 'Hydrolats'], tags: ['taches', 'pores', 'sébum', 'anti-inflammatoire', 'uniformisant'] },

  { id: 'oxyde_zinc', nom: 'Oxyde de zinc', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Protection UV (SPF physique)', 'Antibactérien doux', 'Cicatrisant', 'Opacifiant', 'Anti-inflammatoire'], utilisations: ['Crèmes solaires naturelles', 'Déodorants naturels', 'Soins bébé', 'Traitements acné', 'Poudres cosmétiques'], dosage: '10 à 25% pour protection solaire. 5% pour usage déodorant ou cosmétique.', precautions: 'Blanchit légèrement la peau. Grade non-nano recommandé. Éviter d\'inhaler en poudre.', origine: 'Minéral naturel', odeur: 'Inodore', association: ['Huile de framboise HV', 'Beurre de karité', 'Dioxyde de titane'], tags: ['solaire', 'UV', 'déodorant', 'bébé', 'acné', 'SPF'] },

  { id: 'peptides_cuivre', nom: 'Peptides de cuivre', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Stimulant de la synthèse du collagène', 'Cicatrisant', 'Anti-rides avancé', 'Régénérant', 'Antioxydant'], utilisations: ['Sérums anti-âge avancés', 'Cicatrisation post-traitement', 'Soins anti-rides intensifs'], dosage: '1 à 3% dans vos formulations de sérums.', precautions: 'Ne pas combiner avec vitamine C directe. Excellente tolérance.', origine: 'Synthèse à partir de cuivre et acides aminés', odeur: 'Inodore à légèrement métallique', association: ['Acide hyaluronique', 'Niacinamide'], tags: ['anti-rides', 'collagène', 'régénérant', 'cicatrisant', 'avancé'] },

  { id: 'propolis', nom: 'Propolis', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Antibactérien puissant', 'Antifongique', 'Antiviral', 'Immunostimulant', 'Cicatrisant'], utilisations: ['Soins acné', 'Herpès labial', 'Infections cutanées', 'Soins bucco-dentaires', 'Plaies'], dosage: 'Extrait alcoolique : 5-10 gouttes diluées. Poudre : 1% dans formulations.', precautions: 'Allergie aux produits de la ruche possible. Non végane. Peut tacher.', origine: 'Résine d\'abeilles', odeur: 'Résineuse, miel, caractéristique', association: ['Miel', 'Tea Tree HE', 'Calendula HV'], tags: ['acné', 'herpès', 'antibactérien', 'antiviral', 'cicatrisant'] },

  { id: 'provitamine_b5', nom: 'Provitamine B5 (panthénol)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Hydratant puissant', 'Cicatrisant', 'Réparateur cutané', 'Brillant capillaire', 'Adoucissant'], utilisations: ['Sérums réparateurs', 'Soins après-soleil', 'Après-shampoing', 'Peaux endommagées'], dosage: '1 à 5% dans vos formulations.', precautions: 'Excellente tolérance universelle. Recommandé pour peaux et cheveux fragilisés.', origine: 'Naturel (légumes verts, céréales)', odeur: 'Légèrement sucrée', association: ['Aloe vera', 'Acide hyaluronique', 'Huile d\'argan'], tags: ['hydratant', 'cicatrisant', 'cheveux', 'réparateur', 'après-soleil'] },

  { id: 'retinol_vegetal', nom: 'Bakuchiol (rétinol végétal)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Alternative naturelle au rétinol', 'Anti-rides', 'Stimulant du collagène', 'Anti-taches', 'Toléré par peaux sensibles'], utilisations: ['Sérums anti-âge', 'Soins nuit', 'Peaux sensibles qui ne tolèrent pas le rétinol'], dosage: '0.5 à 2% dans vos formulations de sérums.', precautions: 'Bien plus doux que le rétinol. Peut s\'utiliser pendant grossesse (contrairement au rétinol). Excellente tolérance.', origine: 'Graines de Psoralea corylifolia (plante indienne)', odeur: 'Légèrement végétale', association: ['Rose musquée HV', 'Argan HV', 'Acide hyaluronique'], tags: ['anti-rides', 'collagène', 'anti-taches', 'naturel', 'grossesse', 'sensible'] },

  { id: 'spiruline', nom: 'Spiruline (poudre)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Ultra-nourrissante cutanée', 'Anti-oxydante', 'Illuminatrice de teint', 'Régénérante', 'Riche en protéines et vitamines'], utilisations: ['Masques visage nourrissants', 'Soins anti-âge DIY', 'Masques capillaires protéinés', 'Glow skin'], dosage: '1/4 à 1/2 c. à café dans masques. Colore en vert — rincer soigneusement.', precautions: 'Colore la peau en vert temporairement. Allergie aux algues possible.', origine: 'Algue cyanobactérie (Afrique, Mexique, production mondiale)', odeur: 'Marine, algue concentrée', association: ['Aloe vera', 'Miel', 'Argile blanche'], tags: ['anti-âge', 'masque', 'nourrissant', 'éclat', 'protéines'] },

  { id: 'vitamine_c', nom: 'Vitamine C (acide L-ascorbique)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Antioxydante puissante', 'Anti-taches', 'Illuminatrice de teint', 'Stimulante du collagène', 'Anti-pollution'], utilisations: ['Sérums éclat', 'Soins anti-taches', 'Anti-âge', 'Soins matin'], dosage: '5 à 20% dans sérums anhydres ou aqueux stables (pH 2.5-3.5).', precautions: 'S\'oxyde rapidement — utiliser en petits flacons sombres. Peut piquer légèrement. Photosensibilisant modéré.', origine: 'Naturel (kiwi, acérola, goyave) ou biosynthèse', odeur: 'Légèrement acide citronnée', association: ['Vitamine E', 'Acide hyaluronique', 'Niacinamide'], tags: ['éclat', 'anti-taches', 'antioxydant', 'collagène', 'anti-pollution'] },

  { id: 'vitamine_e', nom: 'Vitamine E (tocophérol)', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Antioxydant puissant', 'Conservateur naturel', 'Anti-rides', 'Protecteur cellulaire', 'Nourrissant'], utilisations: ['Conservateur dans préparations maison', 'Booster anti-âge', 'Cicatrices et vergetures', 'Prévention oxydation huiles'], dosage: '0.5 à 1% dans vos préparations (quelques gouttes). Ajouter en fin de préparation.', precautions: 'Excellente tolérance cutanée.', origine: 'Extraction végétale (soja, germe de blé, tournesol)', odeur: 'Légère, huileuse', association: ['Tous les soins DIY', 'Rose musquée HV', 'Argan HV'], tags: ['antioxydant', 'conservateur', 'anti-rides', 'DIY', 'cicatrices', 'vergetures'] },

  { id: 'zinc', nom: 'Gluconate de zinc', type: 'Actif naturel', categorie: 'Actif', bienfaits: ['Régulateur du sébum', 'Anti-acné', 'Cicatrisant', 'Anti-inflammatoire', 'Antibactérien cutané'], utilisations: ['Soins peaux grasses et acnéiques', 'Sérums anti-imperfections', 'Soins ciblés boutons'], dosage: '0.5 à 2% dans vos formulations.', precautions: 'Excellente tolérance. Peut être légèrement astringent à forte dose.', origine: 'Sel minéral naturel', odeur: 'Inodore', association: ['Niacinamide', 'Acide salicylique', 'Tea Tree HE'], tags: ['acné', 'sébum', 'cicatrisant', 'anti-inflammatoire', 'peau grasse'] },
];

export const CATEGORIES_ACTIFS = [
  { key: 'Tous', label: 'Tous' },
  { key: 'HE', label: 'Huiles essentielles' },
  { key: 'HV', label: 'Huiles végétales' },
  { key: 'Beurre', label: 'Beurres végétaux' },
  { key: 'Hydrolat', label: 'Hydrolats' },
  { key: 'Actif', label: 'Actifs et ingrédients' },
];
