// ════════════════════════════════════════════════════════════════════════════
// BIBLIOTHÈQUE RESPEKTUS® - RECETTES CERTIFIÉES AROMATHÉRAPIE COSMÉTIQUE
// Sources : FFA®, Baudoux, Faucon, Couic-Marinier, Festy, Apoticarius, PubMed
// ════════════════════════════════════════════════════════════════════════════

import { RECETTES_PRO_PACK } from './_recettes_pro-data.js';
import { RECETTES_COMPLEMENTAIRES } from './_recettes_complementaires-data.js';

const RECETTES_BASE = [

  // ════════ CHEVEUX (5) ════════
  {
    id: 'rec_cheveux_vitalite',
    titre: 'Vitalité du cheveu',
    categorie: 'Cheveux',
    sousCategorie: 'Entretien',
    indications: 'Renforce la résistance et l\'imperméabilité du cheveu',
    duree: '21 jours',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Noisette', quantite: '50 ml' },
      { nom: 'HE Citron Jaune Zest', quantite: '3% (30 gouttes)' },
    ],
    etapes: [
      'Mélanger les ingrédients dans un flacon',
      'Masser le cuir chevelu',
      'Appliquer des racines vers les pointes',
      'Garder toute la nuit, laver le matin',
    ],
    bonus: 'Renfort hebdomadaire : 2% de Citron Jaune Zest + 1% Ylang-Ylang Totum dans HV de Noisette',
    precautions: 'Le Citron Zest est photosensibilisant : ne jamais appliquer avant exposition solaire. Application uniquement le soir.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_cheveux_brillance',
    titre: 'Brillance du cheveu',
    categorie: 'Cheveux',
    sousCategorie: 'Entretien',
    indications: 'Apporte brillance et toucher neutre aux cheveux',
    duree: 'Quotidien',
    frequence: 'À chaque shampoing',
    ingredients: [
      { nom: 'Shampoing neutre', quantite: '200 ml' },
      { nom: 'Huile végétale de Jojoba', quantite: '1 cuillère à soupe' },
      { nom: 'HE Lavande Vraie', quantite: '3 gouttes' },
    ],
    etapes: [
      'Dans le flacon de shampoing, ajouter 1 cuillère à soupe d\'HV de Jojoba',
      'Y déposer au préalable 3 gouttes de Lavande Vraie',
      'Bien agiter avant chaque utilisation',
    ],
    bonus: 'Masque hebdomadaire : Lavande Vraie 3% dans 50% Jojoba + 50% Argan, garder la nuit. Si effet trop gras, utiliser uniquement HV de Noisette.',
    precautions: 'Appliquer par petites touches pour éviter un aspect gras. Préférer un flacon spray pour bonne répartition.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_cheveux_blonds',
    titre: 'Révélation des nuances blondes',
    categorie: 'Cheveux',
    sousCategorie: 'Entretien',
    indications: 'Révèle les reflets blonds (naturels ou colorés) et apaise le cuir chevelu',
    duree: 'Quotidien',
    frequence: 'À chaque shampoing',
    ingredients: [
      { nom: 'Shampoing ou après-shampoing neutre', quantite: '200 ml minimum' },
      { nom: 'HE Camomille Noble', quantite: '10 gouttes' },
    ],
    etapes: [
      'Ajouter les 10 gouttes de Camomille Noble dans le flacon',
      'Bien agiter avant chaque utilisation',
    ],
    bonus: 'Masque révélateur 3x/semaine : 3% Camomille Noble dans HV de Jojoba, à garder la nuit.',
    precautions: 'Bien répartir sur l\'ensemble de la chevelure. Pas d\'allergies aux astéracées.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_cheveux_secs',
    titre: 'Cheveux secs',
    categorie: 'Cheveux',
    sousCategorie: 'Réparation',
    indications: 'Nourrit en profondeur les cheveux secs et abîmés',
    duree: 'Maximum 3 heures',
    frequence: 'Le soir, 1 à 2 fois par semaine',
    ingredients: [
      { nom: 'Huile végétale de Coco', quantite: '50 ml' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '3% (30 gouttes)' },
    ],
    etapes: [
      'Appliquer de la racine jusqu\'aux pointes',
      'Ne PAS appliquer sur le cuir chevelu',
      'Laisser poser maximum 3 heures',
      'Laver avec un shampoing doux (type Mixa Bébé)',
    ],
    precautions: 'Ne pas garder plus de 3 heures. Application en soirée ou journée sans sortie (aspect gras).',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_cheveux_cassants',
    titre: 'Cheveux cassants',
    categorie: 'Cheveux',
    sousCategorie: 'Réparation',
    indications: 'Améliore la microcirculation et renforce la fibre capillaire',
    duree: '3 semaines avec pause de 1 semaine',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Noisette', quantite: '50 ml' },
      { nom: 'HE Romarin à Cinéole', quantite: '2% (20 gouttes)' },
      { nom: 'HE Citron Jaune Zest', quantite: '2% (20 gouttes)' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '2% (20 gouttes)' },
    ],
    etapes: [
      'Bien appliquer sur le cuir chevelu en massant longuement',
      'Appliquer ensuite sur les longueurs',
      'Laisser poser plusieurs heures ou la nuit',
    ],
    precautions: 'Citron Zest photosensibilisant : application le soir uniquement. Romarin contre-indiqué en cas de grossesse, hypertension, épilepsie.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  // ════════ CUIR CHEVELU (8) ════════
  {
    id: 'rec_cc_irritation',
    titre: 'Irritation nerveuse du cuir chevelu',
    categorie: 'Cheveux',
    sousCategorie: 'Cuir chevelu',
    indications: 'Apaise le cuir chevelu irrité par le stress',
    duree: '5 jours puis 10 jours',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Millepertuis', quantite: '50 ml' },
      { nom: 'HE Camomille Noble', quantite: '5% (50 gouttes)' },
    ],
    etapes: [
      'Phase 1 (5 jours) : Appliquer la synergie ci-dessus le soir, garder la nuit',
      'Phase 2 (10 jours suivants) : Camomille Noble 2% + Romarin à Cinéole 2% + Lavande Vraie 2% dans HV de Millepertuis',
    ],
    precautions: 'Diagnostiqué par un médecin obligatoire. Millepertuis photosensibilisant : application le soir uniquement, attendre 8-12h avant exposition solaire.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_cc_pelade',
    titre: 'Pelade idiopathique ou nerveuse',
    categorie: 'Cheveux',
    sousCategorie: 'Cuir chevelu',
    indications: 'Relance microcirculation, renforce capillaires et cheveux',
    duree: '3 semaines avec pause de 1 semaine',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Noisette', quantite: '50 ml' },
      { nom: 'HE Romarin à Cinéole', quantite: '2% (20 gouttes)' },
      { nom: 'HE Citron Jaune Zest', quantite: '2% (20 gouttes)' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '2% (20 gouttes)' },
    ],
    etapes: [
      'Appliquer uniquement le soir sur la zone concernée et sa périphérie',
      'Garder toute la nuit',
      'Application quotidienne pendant 3 semaines',
      'Pause d\'une semaine, puis reprendre',
    ],
    precautions: 'Diagnostic médical obligatoire. Citron Zest photosensibilisant. Contre-indiqué grossesse, épilepsie.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_cc_eczema',
    titre: 'Eczéma du cuir chevelu',
    categorie: 'Cheveux',
    sousCategorie: 'Cuir chevelu',
    indications: 'Calme l\'irritation et favorise la cicatrisation',
    duree: 'Jusqu\'à 5 jours après disparition',
    frequence: '2 fois par jour les 3 premiers jours, puis le soir',
    ingredients: [
      { nom: 'Huile végétale de Calendula', quantite: '50 ml' },
      { nom: 'HE Camomille Noble', quantite: '2% (20 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '2% (20 gouttes)' },
      { nom: 'HE Pin Sylvestre', quantite: '2% (20 gouttes)' },
    ],
    etapes: [
      '3 premiers jours : appliquer matin et soir',
      'Ensuite : application le soir uniquement',
      'Continuer 5 jours après disparition complète',
    ],
    precautions: 'Eczéma diagnostiqué par un médecin. Pin Sylvestre contre-indiqué grossesse, hypertension. La Camomille Noble apaise aussi le stress souvent à l\'origine.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_cc_pellicules',
    titre: 'Pellicules',
    categorie: 'Cheveux',
    sousCategorie: 'Cuir chevelu',
    indications: 'Antifongique, régule le biofilm du cuir chevelu',
    duree: 'Jusqu\'à amélioration',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Jojoba', quantite: '50 ml' },
      { nom: 'HE Tea Tree', quantite: '2% (20 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '2% (20 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '2% (20 gouttes)' },
    ],
    etapes: [
      'Appliquer très légèrement avec le bout des doigts sur le cuir chevelu',
      'Ne PAS appliquer en excès',
      'Possibilité : ajouter 50 gouttes de la synergie dans un flacon de shampoing',
    ],
    precautions: 'Tea Tree et Romarin contre-indiqués grossesse. Test cutané au préalable.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_cc_dermite',
    titre: 'Dermite séborrhéique',
    categorie: 'Cheveux',
    sousCategorie: 'Cuir chevelu',
    indications: 'Action antifongique et régulation du sébum',
    duree: 'Jusqu\'à amélioration',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Jojoba (50%)', quantite: '25 ml' },
      { nom: 'Huile végétale de Nigelle (50%)', quantite: '25 ml' },
      { nom: 'HE Palmarosa OU Tea Tree', quantite: '2% (20 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '1% (10 gouttes)' },
      { nom: 'HE Eucalyptus Radié', quantite: '1% (10 gouttes)' },
    ],
    etapes: [
      'Appliquer le soir sur le cuir chevelu',
      'Possibilité : 50 gouttes de synergie dans le shampoing',
    ],
    precautions: 'Diagnostic médical recommandé. Eucalyptus interdit aux moins de 6 ans. Romarin contre-indiqué grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_cc_psoriasis',
    titre: 'Psoriasis',
    categorie: 'Cheveux',
    sousCategorie: 'Cuir chevelu',
    indications: 'Calme les signaux nerveux, action drainante et apaisante',
    duree: 'Selon évolution',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Millepertuis', quantite: '50 ml' },
      { nom: 'HE Camomille Noble', quantite: '2% (20 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '2% (20 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '2% (20 gouttes)' },
    ],
    etapes: [
      'Appliquer le soir sur les zones',
      'Si composante immunitaire : ajouter 1% de Pin Sylvestre',
      'Possibilité : 50 gouttes dans le shampoing',
    ],
    precautions: 'Diagnostic médical obligatoire. Millepertuis et Romarin photosensibilisants. Pin Sylvestre contre-indiqué grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_cc_poux',
    titre: 'Poux (enfants et adultes)',
    categorie: 'Cheveux',
    sousCategorie: 'Cuir chevelu',
    indications: 'Élimination des poux et apaisement du cuir chevelu',
    duree: 'Curatif 3 jours puis prévention',
    frequence: 'Matin et soir en curatif',
    ingredients: [
      { nom: 'ENFANT 2-6 ans : HV de Coco', quantite: '50 ml' },
      { nom: 'HE Clou de Girofle', quantite: '1% (10 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '1% (10 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '2% (20 gouttes)' },
      { nom: 'HE Camomille Noble (si irrité)', quantite: '1% (10 gouttes)' },
    ],
    etapes: [
      'Appliquer matin et soir sur cuir chevelu et chevelure',
      'Utiliser un peigne à poux',
      'Garder jusqu\'au lavage des cheveux',
      'Renouveler 3 jours en curatif, puis le soir uniquement en prévention',
      'Ne JAMAIS utiliser de vinaigre (irritant)',
    ],
    bonus: 'ENFANT 6+ ans : 2% Clou de Girofle. ADULTE : 3% de chaque HE (Clou Girofle, Romarin, Lavande). Répulsif : Lavande Vraie 5% dans HV de Jojoba/Vanille/Macadamia/Nigelle, dilué 1/3 dans eau dans flacon spray.',
    precautions: 'Si cuir chevelu très irrité, remplacer Clou de Girofle par Camomille Noble. Clou de Girofle très irritant si pur.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_cc_cicatrisation',
    titre: 'Cicatrisation des plaies du cuir chevelu',
    categorie: 'Cheveux',
    sousCategorie: 'Cuir chevelu',
    indications: 'Cicatrisation et action antiseptique légère',
    duree: '10 jours puis adaptation',
    frequence: '2 fois par jour les 10 premiers jours',
    ingredients: [
      { nom: 'Huile végétale de Noisette', quantite: '50 ml' },
      { nom: 'HE Tea Tree', quantite: '1% (10 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '2% (20 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '3% (30 gouttes)' },
    ],
    etapes: [
      '10 premiers jours : 2 applications/jour au coton-tige ou compresse',
      'Ensuite : 1 application par jour',
      'Adaptation : 1 fois par jour, 2 fois par semaine selon évolution',
    ],
    precautions: 'Suivi médical de l\'évolution. Romarin contre-indiqué grossesse, hypertension, épilepsie.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  // ════════ VISAGE ENTRETIEN (10) ════════
  {
    id: 'rec_visage_zone_t',
    titre: 'Brillance de la zone T',
    categorie: 'Visage',
    sousCategorie: 'Entretien',
    indications: 'Régule l\'excès de sébum sur le front, le nez et le menton',
    duree: 'Quotidien',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Noisette', quantite: '30 ml' },
      { nom: 'HE Romarin à Cinéole', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Appliquer le soir sur la zone T',
      'Masser légèrement',
    ],
    precautions: 'Romarin contre-indiqué grossesse, hypertension, épilepsie.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_visage_rides',
    titre: 'Anti-rides',
    categorie: 'Visage',
    sousCategorie: 'Anti-âge',
    indications: 'Régénérant cellulaire, anti-rides',
    duree: '3 semaines avec pause de 1 semaine',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Rose Musquée', quantite: '30 ml' },
      { nom: 'HE Rose de Damas (premier choix)', quantite: '1% (6 gouttes)' },
      { nom: 'HE Géranium Rosat Bourbon (alternative)', quantite: '1% (6 gouttes)' },
      { nom: 'HE Bois de Rose ou Bois de Hô (alternative)', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Appliquer tous les soirs sur les zones concernées',
      'Étendre à la périphérie des rides',
      '3 semaines de soin, 1 semaine de pause',
    ],
    bonus: 'Ordre d\'efficacité : Rose de Damas > Géranium Bourbon > Géranium Égypte > Bois de Rose',
    precautions: 'Choisir Rose de Damas de Bulgarie ou Turquie (qualité minimum 20€/ml). Éviter 1er trimestre grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_visage_jour',
    titre: 'Soin de jour visage',
    categorie: 'Visage',
    sousCategorie: 'Entretien',
    indications: 'Protection du biofilm, action apaisante et astringente',
    duree: 'Quotidien',
    frequence: 'Le matin',
    ingredients: [
      { nom: 'Huile végétale de Jojoba', quantite: '30 ml' },
      { nom: 'HE Lavande Vraie', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Appliquer 3 à 5 gouttes le matin sur peau propre',
      'Masser doucement',
    ],
    bonus: 'Prévient rougeurs, assèchement et survenue d\'acné.',
    precautions: 'Excellente tolérance générale. Test cutané pour peaux très sensibles.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_visage_nuit',
    titre: 'Soin de nuit régénérant',
    categorie: 'Visage',
    sousCategorie: 'Anti-âge',
    indications: 'Relance la microcirculation et régénération nocturne',
    duree: '3 semaines avec pause de 1 semaine',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Carotte (macérât)', quantite: '30 ml' },
      { nom: 'HE Romarin à Cinéole', quantite: '0,5% (3 gouttes)' },
      { nom: 'HE Bois de Rose ou Géranium Bourbon', quantite: '0,5% (3 gouttes)' },
      { nom: 'HE Citron Jaune Zest', quantite: '0,5% (3 gouttes)' },
    ],
    etapes: [
      'Appliquer le soir sur peau propre et sèche',
      '3 semaines de soin, 1 semaine de pause',
    ],
    precautions: 'Citron Zest et Romarin photosensibilisants : respecter délai de 12h avant exposition solaire. Romarin contre-indiqué grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_visage_atopique',
    titre: 'Peau à tendance atopique',
    categorie: 'Visage',
    sousCategorie: 'Peaux sensibles',
    indications: 'Calme et apaise les peaux atopiques, limite les réactions',
    duree: 'Long terme',
    frequence: 'Matin et soir',
    ingredients: [
      { nom: 'Huile végétale de Jojoba (60%)', quantite: '18 ml' },
      { nom: 'Huile végétale de Nigelle (20%)', quantite: '6 ml' },
      { nom: 'Huile végétale de Noisette (20%)', quantite: '6 ml' },
      { nom: 'HE Camomille Noble', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Mélanger les huiles végétales',
      'Ajouter la Camomille Noble',
      'Appliquer matin et soir',
    ],
    precautions: 'Allergie aux astéracées possible avec la Camomille. Tester sur petite zone.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_visage_seche',
    titre: 'Peau sèche visage',
    categorie: 'Visage',
    sousCategorie: 'Hydratation',
    indications: 'Restaure et nourrit les peaux sèches',
    duree: 'Long terme',
    frequence: 'Matin et soir en alternance',
    ingredients: [
      { nom: 'Huile végétale de Coco', quantite: '15 ml' },
      { nom: 'Huile végétale de Jojoba', quantite: '15 ml' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Le soir : HV de Coco + 1% Ylang-Ylang Totum',
      'Le matin : HV de Jojoba + 1% Ylang-Ylang Totum',
      'Alterner un jour sur deux si effet trop gras',
    ],
    bonus: 'Si Ylang-Ylang non supporté : alterner HV de Coco seule et HV de Jojoba seule.',
    precautions: 'Ylang-Ylang puissant : peut donner des maux de tête à forte dose.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_visage_grasse',
    titre: 'Peau grasse visage',
    categorie: 'Visage',
    sousCategorie: 'Régulation sébum',
    indications: 'Régule la production de sébum',
    duree: '4 jours puis pause 1 jour',
    frequence: 'Matin et soir',
    ingredients: [
      { nom: 'Huile végétale de Noisette ou Noyau d\'Abricot', quantite: '30 ml' },
      { nom: 'HE Romarin à Cinéole (ou Eucalyptus Radié)', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Appliquer matin et soir',
      'Pause d\'un jour tous les 4 jours pour éviter dessèchement',
    ],
    precautions: 'Romarin contre-indiqué grossesse, hypertension, épilepsie. Eucalyptus interdit moins de 6 ans.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_visage_cernes',
    titre: 'Anti-cernes',
    categorie: 'Visage',
    sousCategorie: 'Yeux',
    indications: 'Décongestionne les cernes marqués',
    duree: 'Ponctuel',
    frequence: 'Selon besoin (pas quotidien)',
    ingredients: [
      { nom: 'Huile végétale de Noisette', quantite: '10 ml' },
      { nom: 'HE Menthe Poivrée', quantite: '1% (2 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '0,5% (1 goutte)' },
    ],
    etapes: [
      'Masser énergiquement les zones cernées',
      'NE PAS appliquer à l\'intérieur de l\'œil',
      'Réserver aux jours où les cernes sont marqués',
    ],
    precautions: 'Menthe Poivrée INTERDITE moins de 7 ans, femmes enceintes, épileptiques. Très puissante : éviter contact yeux.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_visage_raffermissement',
    titre: 'Raffermissement du derme',
    categorie: 'Visage',
    sousCategorie: 'Anti-âge',
    indications: 'Raffermit et tonifie la peau du visage',
    duree: 'Long terme, alternance',
    frequence: '1 jour sur 2',
    ingredients: [
      { nom: 'JOUR 1 : HV de Noisette + Géranium Bourbon ou Égypte 1%', quantite: '30 ml + 6 gouttes' },
      { nom: 'JOUR 2 : HV Rose Musquée 50% + Calophylle 10% + Carotte 40%', quantite: '30 ml total' },
      { nom: 'HE Lavande Vraie', quantite: '1% (6 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '0,5% (3 gouttes)' },
    ],
    etapes: [
      'Préparer 2 mélanges et alterner 1 jour sur 2',
      'Appliquer le soir',
    ],
    bonus: 'De temps en temps avec la première synergie : ajouter une trace de Cyprès Toujours Vert.',
    precautions: 'Romarin et Cyprès contre-indiqués grossesse. Géranium éviter 1er trimestre.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_visage_levres',
    titre: 'Soin des lèvres',
    categorie: 'Visage',
    sousCategorie: 'Lèvres',
    indications: 'Maintient souplesse et douceur des lèvres',
    duree: 'Quotidien',
    frequence: 'Matin et soir',
    ingredients: [
      { nom: 'Macérât huileux de Vanille', quantite: '5 ml' },
    ],
    etapes: [
      'Appliquer une noisette d\'HV de Vanille sur les lèvres',
      'Matin et soir',
    ],
    bonus: 'Laisse aussi un baiser sucré ! 💋',
    precautions: 'Excellente tolérance.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  // ════════ VISAGE RÉPARATION (4) ════════
  {
    id: 'rec_visage_couperose',
    titre: 'Couperose',
    categorie: 'Visage',
    sousCategorie: 'Réparation',
    indications: 'Renforce la résistance des capillaires (action vitamine P-like)',
    duree: '15 jours avec pause de 3 jours',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Noisette', quantite: '30 ml' },
      { nom: 'HE Citron Jaune Zest', quantite: '2 à 3% (12-18 gouttes)' },
      { nom: 'PHASE PAUSE : HV de Millepertuis', quantite: '30 ml' },
      { nom: 'HE Lavande Vraie (pendant pause)', quantite: '3% (18 gouttes)' },
    ],
    etapes: [
      '15 jours : Citron Zest 2-3% dans HV Noisette, le soir',
      '3 jours pause : HV Millepertuis + 3% Lavande Vraie le soir',
      'Reprendre le cycle',
    ],
    precautions: 'Citron Zest ET Millepertuis photosensibilisants : application le soir uniquement, attendre 8-12h avant exposition solaire.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_visage_acne',
    titre: 'Acné',
    categorie: 'Visage',
    sousCategorie: 'Réparation',
    indications: 'Apaise, traite l\'acné, action antibactérienne et cicatrisante',
    duree: 'Long terme',
    frequence: 'Matin et soir',
    ingredients: [
      { nom: 'Huile végétale de Jojoba', quantite: '30 ml' },
      { nom: 'HE Camomille Noble', quantite: '1% (6 gouttes)' },
      { nom: 'HE Tea Tree', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Appliquer matin et soir',
      'De temps en temps : remplacer Camomille Noble par Lavande Vraie',
    ],
    bonus: 'Seules 2 HE sont vraiment efficaces sur l\'acné : Camomille Noble (apaisante) et Tea Tree (antibactérien).',
    precautions: 'Tea Tree contre-indiqué grossesse. Test cutané obligatoire.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_visage_apres_soleil',
    titre: 'Soin apaisant après-soleil visage',
    categorie: 'Visage',
    sousCategorie: 'Réparation',
    indications: 'Apaise et répare la peau après exposition solaire',
    duree: 'Selon besoin',
    frequence: 'Après exposition solaire (pas avant !)',
    ingredients: [
      { nom: 'Huile végétale de Millepertuis (33%)', quantite: '10 ml' },
      { nom: 'Huile végétale de Jojoba (33%)', quantite: '10 ml' },
      { nom: 'Huile végétale de Carotte (33%)', quantite: '10 ml' },
      { nom: 'HE Camomille Noble', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Mélanger les 3 huiles végétales',
      'Ajouter la Camomille Noble',
      'Appliquer après la douche, le soir',
    ],
    precautions: 'PAS d\'exposition au soleil après application (Millepertuis très photosensibilisant).',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_visage_levres_gercees',
    titre: 'Lèvres gercées',
    categorie: 'Visage',
    sousCategorie: 'Lèvres',
    indications: 'Répare et nourrit les lèvres très sèches/gercées',
    duree: 'Selon besoin',
    frequence: 'Plusieurs fois par jour',
    ingredients: [
      { nom: 'HV de Coco OU Beurre de Karité', quantite: '10 ml' },
      { nom: 'HE Lavande Vraie OU Géranium Rosat OU Bois de Rose', quantite: '1% (2 gouttes)' },
    ],
    etapes: [
      'Mélanger HV de Coco fondue + HE de votre choix',
      'Appliquer plusieurs fois par jour',
      'Au choix selon disponibilité : Lavande, Géranium ou Bois de Rose',
    ],
    bonus: 'Si moyens : utiliser 1% de Rose de Damas pour un soin de luxe.',
    precautions: 'Géranium éviter 1er trimestre grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  // ════════ CORPS ENTRETIEN (10) ════════
  {
    id: 'rec_corps_dynamisant',
    titre: 'Soin corps dynamisant',
    categorie: 'Corps',
    sousCategorie: 'Bien-être',
    indications: 'Dynamise le corps et l\'esprit (matin/journée)',
    duree: 'Quotidien',
    frequence: 'Matin ou journée',
    ingredients: [
      { nom: 'HV de Noisette ou Noyau d\'Abricot ou Jojoba', quantite: '50 ml' },
      { nom: 'HE Romarin à Cinéole', quantite: '1% (10 gouttes)' },
      { nom: 'HE Pin Sylvestre', quantite: '1% (10 gouttes)' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '1% (10 gouttes)' },
    ],
    etapes: [
      'Appliquer en massage tonique',
      'Sur l\'ensemble du corps comme un lait corporel',
    ],
    precautions: 'Romarin et Pin Sylvestre contre-indiqués grossesse, hypertension, épilepsie.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_corps_relaxant',
    titre: 'Soin corps relaxant',
    categorie: 'Corps',
    sousCategorie: 'Bien-être',
    indications: 'Détend le corps et l\'esprit',
    duree: 'Quotidien',
    frequence: 'Soir',
    ingredients: [
      { nom: 'HV de Noyau d\'Abricot (50%)', quantite: '25 ml' },
      { nom: 'HV de Vanille (50%)', quantite: '25 ml' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '1% (10 gouttes)' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '1% (10 gouttes)' },
      { nom: 'HE Bois de Rose ou Bois de Hô', quantite: '1% (10 gouttes)' },
    ],
    etapes: [
      'Appliquer en massage lent et relaxant',
      'Sur l\'ensemble du corps',
    ],
    precautions: 'Bois de Rose : préférer Bois de Hô (espèce non menacée).',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_corps_dodo',
    titre: 'Soin corps "Dodo" (sommeil)',
    categorie: 'Corps',
    sousCategorie: 'Bien-être',
    indications: 'Favorise l\'endormissement, sédatif',
    duree: 'Avant le coucher',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Millepertuis', quantite: '50 ml' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '1% (10 gouttes)' },
      { nom: 'HE Mandarine Zest', quantite: '1% (10 gouttes)' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '1% (10 gouttes)' },
    ],
    etapes: [
      'Après la douche du soir',
      'Appliquer en massage doux',
    ],
    precautions: 'Sédatif - ne rien prévoir après. Si hypotension, ajouter 1% de Romarin Cinéole. Millepertuis photosensibilisant.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_corps_seduction',
    titre: 'Soin corps "Séduction"',
    categorie: 'Corps',
    sousCategorie: 'Bien-être',
    indications: 'Touche olfactive séduction et entretien cutané',
    duree: 'Selon désir',
    frequence: 'Soirée',
    ingredients: [
      { nom: 'Huile végétale de Vanille', quantite: '50 ml' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '1% (10 gouttes)' },
      { nom: 'HE Rose de Damas', quantite: '1% (10 gouttes)' },
      { nom: 'HE Absolu de Jasmin', quantite: '1% (10 gouttes)' },
    ],
    etapes: [
      'Appliquer en massage sensuel',
      'Sur les zones du corps souhaitées',
    ],
    precautions: 'Rose de Damas et Jasmin précieux. Éviter 1er trimestre grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_corps_seche',
    titre: 'Peau sèche corps',
    categorie: 'Corps',
    sousCategorie: 'Hydratation',
    indications: 'Restaure le biofilm et la souplesse cutanée',
    duree: 'Selon évolution',
    frequence: '2 fois par jour les 3 premiers jours, puis 1 fois par jour',
    ingredients: [
      { nom: 'HV de Macadamia (70%)', quantite: '35 ml' },
      { nom: 'HV de Jojoba (20%)', quantite: '10 ml' },
      { nom: 'HV de Coco (10%)', quantite: '5 ml' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '1% (10 gouttes)' },
    ],
    etapes: [
      '3 premiers jours : 2 applications par jour',
      'Ensuite : 1 application par jour',
    ],
    precautions: 'Excellente tolérance.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_corps_atopique',
    titre: 'Peau atopique corps',
    categorie: 'Corps',
    sousCategorie: 'Peaux sensibles',
    indications: 'Apaise les peaux réactives et atopiques',
    duree: '10 jours puis adaptation',
    frequence: 'Matin et soir 10 jours, puis 1x/jour',
    ingredients: [
      { nom: 'MATIN : HV de Jojoba', quantite: '30 ml' },
      { nom: 'SOIR : HV Jojoba 50% + Millepertuis 50%', quantite: '30 ml' },
      { nom: 'HE Camomille Noble', quantite: '1% (6 gouttes)' },
      { nom: 'OPTIONNEL : Pin Sylvestre + Lavande Vraie', quantite: '1% chaque' },
    ],
    etapes: [
      '10 premiers jours : matin et soir',
      'Ensuite : 1 fois par jour',
      'Long terme : 2 à 3 jours par semaine',
    ],
    precautions: 'Diagnostic médical recommandé. Millepertuis photosensibilisant : application soir uniquement.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_corps_mains',
    titre: 'Soin des mains',
    categorie: 'Corps',
    sousCategorie: 'Mains',
    indications: 'Entretien et prévention du dessèchement hivernal',
    duree: 'Quotidien',
    frequence: 'Selon besoin',
    ingredients: [
      { nom: 'Huile végétale de Jojoba', quantite: '30 ml' },
      { nom: 'HE Lavande Vraie', quantite: '1% (6 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Appliquer quelques gouttes',
      'Masser jusqu\'à pénétration complète',
    ],
    precautions: 'Romarin contre-indiqué grossesse, hypertension, épilepsie.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_corps_pieds',
    titre: 'Soin des pieds (anti-mycoses)',
    categorie: 'Corps',
    sousCategorie: 'Pieds',
    indications: 'Entretien des pieds, prévention mycoses',
    duree: 'Quotidien',
    frequence: 'Soir',
    ingredients: [
      { nom: 'Huile végétale de Jojoba', quantite: '30 ml' },
      { nom: 'HE Palmarosa', quantite: '1% (6 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '1% (6 gouttes)' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Le soir, masser les pieds',
      'Insister entre les orteils (prévention mycoses)',
    ],
    precautions: 'Bonne tolérance générale.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  // ════════ CORPS RÉPARATION (6) ════════
  {
    id: 'rec_corps_apres_soleil',
    titre: 'Après-soleil corps',
    categorie: 'Corps',
    sousCategorie: 'Réparation',
    indications: 'Apaise et répare le corps après exposition solaire',
    duree: 'Après exposition',
    frequence: 'Le soir uniquement',
    ingredients: [
      { nom: 'HV de Millepertuis (80%)', quantite: '40 ml' },
      { nom: 'HV de Carotte (20%)', quantite: '10 ml' },
      { nom: 'HE Lavande Vraie', quantite: '1% (10 gouttes)' },
      { nom: 'HE Camomille Noble', quantite: '2% (20 gouttes)' },
    ],
    etapes: [
      'Le soir uniquement',
      'Appliquer sur l\'ensemble du corps exposé',
    ],
    bonus: 'Variantes : remplacer Carotte par Jojoba ou Coco si peau très sèche.',
    precautions: 'Millepertuis photosensibilisant : pas d\'exposition solaire 8-12h après. JAMAIS le matin.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_corps_apres_epilation',
    titre: 'Après épilation',
    categorie: 'Corps',
    sousCategorie: 'Réparation',
    indications: 'Calme la sensation de brûlure et l\'irritation',
    duree: 'Après épilation',
    frequence: 'Une fois après épilation',
    ingredients: [
      { nom: 'Huile végétale de Nigelle', quantite: '30 ml' },
      { nom: 'HE Camomille Noble', quantite: '2% (12 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '2% (12 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '2% (12 gouttes)' },
      { nom: 'HE Menthe Poivrée', quantite: '0,5% (3 gouttes)' },
    ],
    etapes: [
      'Appliquer en massage doux',
      'Sur les zones épilées',
    ],
    precautions: 'Menthe Poivrée INTERDITE moins de 7 ans, grossesse, épilepsie.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_corps_cellulite',
    titre: 'Cellulite (Minceur)',
    categorie: 'Minceur',
    sousCategorie: 'Cellulite',
    indications: 'Action drainante et lipolytique sur la cellulite',
    duree: '3 semaines avec pause de 1 semaine',
    frequence: 'Le soir (ou matin et soir si non exposé au soleil)',
    ingredients: [
      { nom: 'Huile végétale de Noisette', quantite: '50 ml' },
      { nom: 'HE Cèdre d\'Atlas', quantite: '5% (50 gouttes)' },
      { nom: 'HE Cyprès Toujours Vert', quantite: '5% (50 gouttes)' },
      { nom: 'HE Citron Jaune Zest', quantite: '5% (50 gouttes)' },
    ],
    etapes: [
      'Massage énergique après la douche',
      'Insister sur les zones de cellulite (cuisses, fesses, ventre)',
      '3 semaines de cure puis 1 semaine de pause',
    ],
    precautions: 'Citron Zest photosensibilisant. Cèdre et Cyprès contre-indiqués grossesse. Réduire fréquence selon amélioration.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_corps_vergetures',
    titre: 'Vergetures',
    categorie: 'Corps',
    sousCategorie: 'Réparation',
    indications: 'Atténue et prévient les vergetures',
    duree: '3 semaines avec pause de 1 semaine',
    frequence: 'Matin et soir',
    ingredients: [
      { nom: 'Huile végétale de Rose Musquée', quantite: '50 ml' },
      { nom: 'HE Géranium Rosat Égypte ou Bourbon', quantite: '3% (30 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '3% (30 gouttes)' },
    ],
    etapes: [
      'Appliquer matin et soir sur zones concernées',
      '3 semaines de soin, 1 semaine de pause',
      'Réduire à 1 application par jour selon amélioration',
    ],
    precautions: 'Géranium éviter 1er trimestre grossesse. Pour vergetures de grossesse, utiliser à partir du 4ème mois.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_corps_gercures_mains',
    titre: 'Gerçures et crevasses des mains',
    categorie: 'Corps',
    sousCategorie: 'Mains',
    indications: 'Répare les gerçures profondes des mains',
    duree: 'Selon évolution',
    frequence: 'Maximum 3 fois par jour',
    ingredients: [
      { nom: 'HV de Rose Musquée (80%)', quantite: '40 ml' },
      { nom: 'HV de Coco (20%)', quantite: '10 ml' },
      { nom: 'HE Géranium Rosat Égypte ou Bourbon', quantite: '5% (50 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '5% (50 gouttes)' },
      { nom: 'HE Camomille Noble', quantite: '5% (50 gouttes)' },
    ],
    etapes: [
      'Appliquer selon le besoin',
      'Maximum 3 fois par jour',
      'Insister sur les crevasses',
    ],
    precautions: 'Géranium éviter 1er trimestre. Allergie astéracées (Camomille).',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_corps_gercures_talon',
    titre: 'Gerçures du talon',
    categorie: 'Corps',
    sousCategorie: 'Pieds',
    indications: 'Répare les gerçures profondes des talons',
    duree: 'Selon évolution',
    frequence: 'Matin et soir, à diminuer',
    ingredients: [
      { nom: 'HV de Coco OU Beurre de Karité', quantite: '50 ml' },
      { nom: 'HE Ciste', quantite: '5% (50 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '5% (50 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '5% (50 gouttes)' },
    ],
    etapes: [
      'Matin et soir, masser les talons',
      'Insister sur les zones gercées',
      'Diminuer fréquence selon évolution',
    ],
    precautions: 'Ciste contre-indiqué grossesse, allaitement, anticoagulants. Romarin contre-indiqué grossesse, hypertension, épilepsie.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  // ════════ TOILETTE FEMME (4) ════════
  {
    id: 'rec_femme_parfum_envoutant',
    titre: 'Parfum envoûtant (femme)',
    categorie: 'Toilette',
    sousCategorie: 'Parfum',
    indications: 'Parfum naturel sans alcool, envoûtant',
    duree: 'À volonté',
    frequence: 'Selon envie',
    ingredients: [
      { nom: 'Huile végétale de Jojoba', quantite: '30 ml' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '1% (6 gouttes)' },
      { nom: 'HE Patchouli', quantite: '1% (6 gouttes)' },
      { nom: 'HE Palmarosa', quantite: '0,5% (3 gouttes)' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '0,5% (3 gouttes)' },
    ],
    etapes: [
      'Mélanger les ingrédients',
      'Laisser macérer 24h',
      'Appliquer sur points pulsation (cou, poignets)',
    ],
    bonus: 'Variantes disponibles : parfum classique, parfum frais (avec Laurier Noble), pour femme âgée (avec Bois de Rose).',
    precautions: 'Patchouli déconseillé 1er trimestre grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_femme_deodorant',
    titre: 'Déodorant naturel femme',
    categorie: 'Toilette',
    sousCategorie: 'Déodorant',
    indications: 'Empêche les mauvaises odeurs sans bloquer la transpiration',
    duree: 'Quotidien',
    frequence: 'Matin',
    ingredients: [
      { nom: 'Huile végétale de Noisette', quantite: '30 ml' },
      { nom: 'HE Palmarosa', quantite: '1% (6 gouttes)' },
      { nom: 'ALTERNANCE : HE Petit-Grain Bigarade', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Préparer 2 flacons (Palmarosa et Petit-Grain Bigarade)',
      'Alterner toutes les semaines',
      'Appliquer sous les aisselles propres',
    ],
    bonus: 'La transpiration est un processus naturel, pas un problème : on lutte contre les odeurs, pas contre le mécanisme.',
    precautions: 'Test cutané au préalable. Bonne tolérance générale.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_femme_gel_douche',
    titre: 'Gel douche femme',
    categorie: 'Toilette',
    sousCategorie: 'Hygiène',
    indications: 'Gel douche tonifiant et nourrissant',
    duree: 'Quotidien',
    frequence: 'Douche',
    ingredients: [
      { nom: 'Base lavante neutre', quantite: '200 ml' },
      { nom: 'Huile végétale de Noyau d\'Abricot', quantite: '5 ml' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '3% (15 gouttes)' },
      { nom: 'HE Géranium Rosat Égypte ou Bourbon', quantite: '3% (15 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '3% (15 gouttes)' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '1% (5 gouttes)' },
    ],
    etapes: [
      'Préparer la synergie HE dans HV',
      'Mettre 100 gouttes de la synergie dans 200 ml de base lavante neutre',
      'Bien agiter avant chaque utilisation',
    ],
    precautions: 'Romarin contre-indiqué grossesse. Géranium éviter 1er trimestre.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_femme_shampoing',
    titre: 'Shampoing femme',
    categorie: 'Toilette',
    sousCategorie: 'Shampoing',
    indications: 'Shampoing tonifiant et brillance',
    duree: 'Quotidien',
    frequence: 'À chaque shampoing',
    ingredients: [
      { nom: 'Base de shampoing neutre', quantite: '200 ml' },
      { nom: 'Huile végétale de Jojoba', quantite: '5 ml' },
      { nom: 'HE Romarin à Cinéole', quantite: '3% (15 gouttes)' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '3% (15 gouttes)' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '2% (10 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '1% (5 gouttes)' },
      { nom: 'HE Citron Jaune Zest', quantite: '1% (5 gouttes)' },
    ],
    etapes: [
      'Préparer la synergie HE dans HV',
      '100 gouttes de synergie dans 200 ml de base shampoing',
      'Agiter avant chaque utilisation',
    ],
    precautions: 'Citron Zest photosensibilisant : éviter exposition solaire après usage. Romarin contre-indiqué grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  // ════════ HOMME (8) ════════
  {
    id: 'rec_homme_jour',
    titre: 'Soin de jour visage homme',
    categorie: 'Homme',
    sousCategorie: 'Visage',
    indications: 'Hydratation et protection quotidienne',
    duree: 'Quotidien',
    frequence: 'Le matin',
    ingredients: [
      { nom: 'HV de Noyau d\'Abricot ou Jojoba', quantite: '30 ml' },
      { nom: 'HE Lavande Vraie', quantite: '0,3% (2 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '0,3% (2 gouttes)' },
      { nom: 'HE Bois de Rose ou Bois de Hô', quantite: '0,3% (2 gouttes)' },
    ],
    etapes: [
      '1% total des 3 HE combinées dans HV',
      'Appliquer le matin sur peau propre',
    ],
    precautions: 'Romarin contre-indiqué hypertension, épilepsie.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_homme_nuit',
    titre: 'Soin de nuit visage homme',
    categorie: 'Homme',
    sousCategorie: 'Visage',
    indications: 'Régénération nocturne',
    duree: 'Quotidien',
    frequence: 'Le soir',
    ingredients: [
      { nom: 'Huile végétale de Jojoba', quantite: '30 ml' },
      { nom: 'HE Camomille Noble', quantite: '0,25% (2 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '0,25% (2 gouttes)' },
      { nom: 'HE Bergamote Zest', quantite: '0,25% (2 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '0,25% (2 gouttes)' },
    ],
    etapes: [
      '1% total HE dans HV de Jojoba',
      'Appliquer le soir',
    ],
    precautions: 'Bergamote Zest photosensibilisant : 8-12h avant exposition solaire. Romarin contre-indiqué grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_homme_barbe',
    titre: 'Entretien de la barbe',
    categorie: 'Homme',
    sousCategorie: 'Barbe',
    indications: 'Adoucit, parfume et entretient la barbe',
    duree: 'Quotidien',
    frequence: '1 à 2 fois par jour, 5-6 jours/semaine',
    ingredients: [
      { nom: 'HV de Jojoba (70%)', quantite: '21 ml' },
      { nom: 'HV de Coco (10%)', quantite: '3 ml' },
      { nom: 'HV de Macadamia (10%)', quantite: '3 ml' },
      { nom: 'HV de Vanille (10%)', quantite: '3 ml' },
      { nom: 'HE Gingembre', quantite: '1% (6 gouttes)' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '1% (6 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '1% (6 gouttes)' },
      { nom: 'HE Vétiver', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Mélanger les huiles végétales',
      'Ajouter les huiles essentielles',
      'Appliquer 1-2 fois/jour, 5-6 jours/semaine',
    ],
    precautions: 'Gingembre peut irriter peaux très sensibles. Test au préalable.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_homme_apres_rasage',
    titre: 'Après-rasage',
    categorie: 'Homme',
    sousCategorie: 'Rasage',
    indications: 'Apaise après le rasage, prévient le feu du rasoir',
    duree: 'Après chaque rasage',
    frequence: 'Après le rasage',
    ingredients: [
      { nom: 'HV de Jojoba (80%)', quantite: '24 ml' },
      { nom: 'Beurre de Karité (10%)', quantite: '3 ml fondu' },
      { nom: 'HV de Coco (10%)', quantite: '3 ml' },
      { nom: 'HE Camomille Noble', quantite: '1% (6 gouttes)' },
      { nom: 'HE Lavande Vraie', quantite: '1% (6 gouttes)' },
      { nom: 'HE Pin Sylvestre', quantite: '1% (6 gouttes)' },
      { nom: 'HE Romarin à Cinéole', quantite: '1% (6 gouttes)' },
      { nom: 'OPTIONNEL : HE Menthe Poivrée', quantite: '0,5% (3 gouttes)' },
    ],
    etapes: [
      'Faire fondre le Beurre de Karité',
      'Mélanger avec les HV puis ajouter les HE',
      'Appliquer après le rasage',
    ],
    precautions: 'Pin Sylvestre contre-indiqué grossesse, hypertension. Menthe Poivrée à partir de 7 ans.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_homme_parfum_boise',
    titre: 'Parfum homme boisé/épicé',
    categorie: 'Homme',
    sousCategorie: 'Parfum',
    indications: 'Parfum naturel sans alcool, boisé et masculin',
    duree: 'À volonté',
    frequence: 'Selon envie',
    ingredients: [
      { nom: 'Huile végétale de Jojoba', quantite: '30 ml' },
      { nom: 'HE Pin Sylvestre', quantite: '0,4% (3 gouttes)' },
      { nom: 'HE Cèdre d\'Atlas', quantite: '0,4% (3 gouttes)' },
      { nom: 'HE Vétiver', quantite: '0,4% (3 gouttes)' },
      { nom: 'HE Bois de Rose ou Bois de Hô', quantite: '0,4% (3 gouttes)' },
      { nom: 'HE Gingembre', quantite: '0,4% (3 gouttes)' },
    ],
    etapes: [
      '2% total HE dans HV de Jojoba',
      'Laisser macérer 24h',
      'Appliquer sur points de pulsation',
    ],
    bonus: 'Variantes : parfum frais (Romarin/Lavande/Laurier Noble/Pin) ou parfum sucré/épicé (Ylang/Patchouli/Épinette Noire).',
    precautions: 'Pin Sylvestre, Cèdre, Vétiver contre-indiqués grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_homme_deodorant',
    titre: 'Déodorant naturel homme',
    categorie: 'Homme',
    sousCategorie: 'Déodorant',
    indications: 'Anti-odeurs sans bloquer la transpiration',
    duree: 'Quotidien',
    frequence: 'Le matin',
    ingredients: [
      { nom: 'Huile végétale de Jojoba', quantite: '30 ml' },
      { nom: 'HE Tea Tree', quantite: '1% (6 gouttes)' },
      { nom: 'HE Cèdre d\'Atlas', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Mélanger',
      'Appliquer sous les aisselles propres',
    ],
    precautions: 'Tea Tree et Cèdre contre-indiqués grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_homme_gel_douche',
    titre: 'Gel douche homme',
    categorie: 'Homme',
    sousCategorie: 'Hygiène',
    indications: 'Gel douche tonifiant',
    duree: 'Quotidien',
    frequence: 'Douche',
    ingredients: [
      { nom: 'Base lavante neutre', quantite: '200 ml' },
      { nom: 'Huile végétale de Noyau d\'Abricot', quantite: '5 ml' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '3% (15 gouttes)' },
      { nom: 'HE Cèdre d\'Atlas', quantite: '3% (15 gouttes)' },
      { nom: 'HE Gingembre', quantite: '3% (15 gouttes)' },
      { nom: 'HE Pin Sylvestre', quantite: '3% (15 gouttes)' },
    ],
    etapes: [
      'Préparer la synergie HE dans HV',
      '100 gouttes de synergie dans 200 ml de base lavante',
    ],
    precautions: 'Cèdre, Pin Sylvestre, Gingembre : éviter grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },

  {
    id: 'rec_homme_shampoing',
    titre: 'Shampoing homme',
    categorie: 'Homme',
    sousCategorie: 'Shampoing',
    indications: 'Shampoing tonifiant et masculin',
    duree: 'Quotidien',
    frequence: 'À chaque shampoing',
    ingredients: [
      { nom: 'Base de shampoing neutre', quantite: '200 ml' },
      { nom: 'Huile végétale de Jojoba', quantite: '5 ml' },
      { nom: 'HE Romarin à Cinéole', quantite: '3% (15 gouttes)' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '3% (15 gouttes)' },
      { nom: 'HE Cèdre d\'Atlas', quantite: '2% (10 gouttes)' },
      { nom: 'HE Pin Sylvestre', quantite: '1% (5 gouttes)' },
      { nom: 'HE Citron Jaune Zest', quantite: '1% (5 gouttes)' },
    ],
    etapes: [
      'Préparer la synergie HE dans HV',
      '100 gouttes de synergie dans 200 ml de base shampoing',
    ],
    precautions: 'Citron photosensibilisant. Romarin, Cèdre, Pin Sylvestre contre-indiqués grossesse.',
    source: 'FFA® - Praticien Aromathérapie Cosmétique',
  },


  // ════════ BIEN-ÊTRE ÉMOTIONNEL (18) - Sources scientifiques ════════
  {
    id: 'rec_bien_anxiete',
    titre: 'Apaisement de l\'anxiété',
    categorie: 'Bien-être',
    sousCategorie: 'Anxiété',
    indications: 'Apaise l\'anxiété et le stress quotidien, réduit les tensions nerveuses',
    duree: 'Selon besoin',
    frequence: '2 à 3 fois par jour ou aux moments de tension',
    ingredients: [
      { nom: 'HE Lavande Vraie', quantite: '2 gouttes' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '1 goutte' },
      { nom: 'HE Camomille Romaine', quantite: '1 goutte' },
      { nom: 'Stick inhalateur ou mouchoir', quantite: '1' },
    ],
    etapes: [
      'Déposer les huiles essentielles sur la mèche du stick inhalateur (ou un mouchoir)',
      'Inspirer profondément 3 fois par narine en alternance',
      'Recommencer toutes les 2 heures ou aux moments de tension',
      'Pour la nuit : 2 gouttes sur l\'oreiller',
    ],
    bonus: 'Massage anti-stress : 5 gouttes Lavande Vraie + 3 gouttes Petit-Grain dans 30 ml HV de Noyau d\'Abricot, masser le plexus solaire et les poignets.',
    precautions: 'Méta-analyse 2020 (Journal of Affective Disorders, 32 essais cliniques) : effet significatif sur l\'anxiété. Contre-indiqué 1er trimestre grossesse. Consulter un professionnel si anxiété chronique.',
    source: 'Méta-analyse Journal of Affective Disorders (2020)',
  },

  {
    id: 'rec_bien_depression_legere',
    titre: 'Soutien émotionnel - humeur basse',
    categorie: 'Bien-être',
    sousCategorie: 'Soutien émotionnel',
    indications: 'Soutien émotionnel en complément d\'un suivi médical (ne remplace pas un traitement)',
    duree: 'Cure de 30 jours',
    frequence: 'Diffusion quotidienne 30 min, matin et fin de journée',
    ingredients: [
      { nom: 'HE Bergamote', quantite: '4 gouttes' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '2 gouttes' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '3 gouttes' },
      { nom: 'HE Lavande Vraie', quantite: '3 gouttes' },
    ],
    etapes: [
      'Mettre le mélange dans un diffuseur ultrasonique',
      'Diffuser 30 minutes le matin et 30 minutes en fin d\'après-midi',
      'Pratiquer pendant 30 jours minimum (effets démontrés sur cette durée)',
      'Compléter avec un massage soir : 1% du mélange dans HV Noyau d\'Abricot, sur plexus et poignets',
    ],
    bonus: 'Étude iranienne : inhalation 30 nuits consécutives → baisse significative de la dépression, anxiété, stress, effets persistants 1 mois après. Combiner avec activité physique douce et lumière naturelle.',
    precautions: 'IMPORTANT : ne remplace JAMAIS un traitement médical. Si humeur basse persistante, consulter un médecin/psychologue/psychiatre. Bergamote photosensibilisante : pas d\'application avant exposition solaire.',
    source: 'Essai clinique randomisé iranien (lavande/camomille, 30 nuits) - Journal of Affective Disorders (2020)',
  },

  {
    id: 'rec_bien_arret_tabac',
    titre: 'Soutien arrêt du tabac',
    categorie: 'Bien-être',
    sousCategorie: 'Sevrage',
    indications: 'Réduit l\'envie de fumer (craving), apaise l\'anxiété du sevrage',
    duree: 'Pendant toute la durée du sevrage',
    frequence: 'À chaque envie de fumer (max 3 inspirations profondes)',
    ingredients: [
      { nom: 'HE Poivre Noir (Piper nigrum)', quantite: '5 à 10 gouttes' },
      { nom: 'HE Menthe Poivrée', quantite: '3 gouttes' },
      { nom: 'HE Lavande Vraie', quantite: '3 gouttes' },
      { nom: 'Stick inhalateur (mèche en coton)', quantite: '1' },
    ],
    etapes: [
      'Déposer les HE sur la mèche du stick inhalateur',
      'À chaque envie de fumer : ouvrir le stick et faire 3 inspirations profondes par la bouche (max)',
      'Le Poivre Noir reproduit la sensation de fumée dans la gorge et coupe le craving',
      'Compléter avec massage matin du plexus : 1 goutte Mandarine + 1 goutte Romarin Cinéole dans HV',
    ],
    bonus: 'Étude clinique de Rose (1994) : inhalation de Poivre Noir réduit significativement le craving et prolonge le délai avant la prochaine cigarette. Étude japonaise sur fumeurs avec dépression : aromathérapie atténue symptômes du sevrage.',
    precautions: 'Menthe Poivrée INTERDITE moins de 7 ans, grossesse, épilepsie. Poivre Noir : ne pas dépasser 3 inspirations à chaque prise, peut être légèrement irritant. Toujours associer à un suivi médical (tabacologue, médecin).',
    source: 'Rose JE, Behm FM (1994) - Drug and Alcohol Dependence ; Études cliniques publiées',
  },

  {
    id: 'rec_bien_sommeil',
    titre: 'Sommeil profond et réparateur',
    categorie: 'Bien-être',
    sousCategorie: 'Sommeil',
    indications: 'Favorise l\'endormissement, améliore la qualité du sommeil, calme les pensées',
    duree: 'Cure 21 jours puis selon besoin',
    frequence: 'Chaque soir au coucher',
    ingredients: [
      { nom: 'HE Lavande Vraie', quantite: '5 gouttes' },
      { nom: 'HE Camomille Romaine', quantite: '2 gouttes' },
      { nom: 'HE Marjolaine à Coquilles', quantite: '2 gouttes' },
      { nom: 'HE Mandarine Zest', quantite: '3 gouttes' },
    ],
    etapes: [
      'Diffusion : 6-8 gouttes dans diffuseur 30 min avant coucher (chambre seulement)',
      'OU : 2 gouttes Lavande Vraie pure sur l\'oreiller',
      'OU : Massage plexus + nuque avec 2 gouttes du mélange dans 5 ml HV de Macadamia',
      'Cure de 21 jours pour résultats durables',
    ],
    bonus: 'Études cliniques : la Lavande Vraie (linalol/acétate de linalyle) augmente le sommeil profond et réduit le temps d\'endormissement. La Marjolaine apaise le système nerveux parasympathique.',
    precautions: 'Mandarine Zest photosensibilisante (pas avant sortie). Marjolaine déconseillée grossesse 1er trimestre. Si insomnie chronique, consulter un médecin du sommeil.',
    source: 'Études cliniques sommeil et lavande - PubMed (multiples études)',
  },

  {
    id: 'rec_bien_burnout',
    titre: 'Récupération après burn-out',
    categorie: 'Bien-être',
    sousCategorie: 'Fatigue',
    indications: 'Soutien des surrénales, anti-fatigue profonde, récupération nerveuse',
    duree: 'Cure de 3 semaines + 1 semaine pause',
    frequence: 'Matin et midi',
    ingredients: [
      { nom: 'Huile végétale de Macadamia', quantite: '30 ml' },
      { nom: 'HE Épinette Noire', quantite: '1% (6 gouttes)' },
      { nom: 'HE Pin Sylvestre', quantite: '1% (6 gouttes)' },
      { nom: 'HE Bergamote', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Préparer le mélange dans un flacon teinté',
      'Matin et midi : massage au-dessus des reins (zone des surrénales) avec 5-10 gouttes',
      'Cure 3 semaines, pause 1 semaine, reprendre si besoin',
      'NE PAS utiliser le soir (effet tonique)',
    ],
    bonus: 'L\'Épinette Noire et le Pin Sylvestre ont une action "cortisone-like" qui stimule naturellement les surrénales fatiguées. À combiner avec sommeil, alimentation équilibrée et accompagnement médical.',
    precautions: 'CONTRE-INDIQUÉS grossesse, allaitement, hypertension, enfants moins de 6 ans. Bergamote photosensibilisante (matin = OK si protection UV, midi = pas avant exposition). Burn-out = consulter médecin obligatoirement.',
    source: 'Aromathérapie professionnelle - Franchomme & Baudoux',
  },

  {
    id: 'rec_bien_concentration',
    titre: 'Concentration et clarté mentale',
    categorie: 'Bien-être',
    sousCategorie: 'Concentration',
    indications: 'Stimule la concentration, améliore la mémoire, lutte contre la fatigue mentale',
    duree: 'Selon besoin',
    frequence: 'Matin ou avant tâche intellectuelle',
    ingredients: [
      { nom: 'HE Romarin à Cinéole', quantite: '4 gouttes' },
      { nom: 'HE Menthe Poivrée', quantite: '2 gouttes' },
      { nom: 'HE Citron Jaune Zest', quantite: '4 gouttes' },
    ],
    etapes: [
      'Diffuser 15-20 minutes dans le bureau ou espace de travail',
      'OU : 1 goutte Menthe Poivrée + 1 goutte Romarin sur un mouchoir, inhaler 3 fois',
      'À utiliser le matin et avant les périodes de concentration',
      'NE PAS utiliser le soir (effet stimulant)',
    ],
    bonus: 'Étude Northumbria University (2003) : l\'inhalation de Romarin à Cinéole améliore mémoire et performances cognitives. Le 1,8-cinéole agit sur l\'acétylcholine cérébrale.',
    precautions: 'Menthe Poivrée et Romarin INTERDITS moins de 7 ans, grossesse, épilepsie, hypertension. Citron Zest photosensibilisant : ne pas appliquer sur peau exposée au soleil.',
    source: 'Northumbria University - Moss et al. (2003) - International Journal of Neuroscience',
  },

  {
    id: 'rec_bien_confiance',
    titre: 'Confiance en soi et prise de parole',
    categorie: 'Bien-être',
    sousCategorie: 'Confiance',
    indications: 'Renforce la confiance, apaise le trac avant prise de parole, examen, entretien',
    duree: 'Ponctuel',
    frequence: '15-30 minutes avant l\'événement',
    ingredients: [
      { nom: 'HE Laurier Noble', quantite: '2 gouttes' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '2 gouttes' },
      { nom: 'HE Bergamote', quantite: '2 gouttes' },
      { nom: 'Stick inhalateur', quantite: '1' },
    ],
    etapes: [
      'Préparer le stick inhalateur avec les 6 gouttes',
      '15-30 min avant l\'événement : 3 inspirations profondes',
      'Visualiser la réussite pendant l\'inhalation (ancrage)',
      'Recommencer si besoin avant et pendant l\'événement',
    ],
    bonus: 'Le Laurier Noble est traditionnellement utilisé pour la "confiance des champions". Combiner avec respiration carrée (4 sec inspiration, 4 sec rétention, 4 sec expiration, 4 sec rétention) pour décupler l\'effet.',
    precautions: 'Laurier Noble contre-indiqué grossesse, allaitement, asthme, allergie aux Lauracées. Bergamote photosensibilisante.',
    source: 'Aromathérapie traditionnelle - Festy D., Faucon M.',
  },

  {
    id: 'rec_bien_choc_emotionnel',
    titre: 'Apaisement après choc émotionnel',
    categorie: 'Bien-être',
    sousCategorie: 'Soutien émotionnel',
    indications: 'Apaisement immédiat après choc, deuil, séparation, mauvaise nouvelle',
    duree: 'Selon besoin',
    frequence: 'Toutes les 1-2h les premiers jours',
    ingredients: [
      { nom: 'HE Camomille Romaine', quantite: '2 gouttes' },
      { nom: 'HE Lavande Vraie', quantite: '2 gouttes' },
      { nom: 'HE Néroli (Fleur d\'Oranger)', quantite: '1 goutte' },
      { nom: 'HV Noyau d\'Abricot', quantite: '5 ml' },
    ],
    etapes: [
      'Mélanger les ingrédients dans un petit flacon roll-on',
      'Appliquer sur les poignets et le plexus solaire',
      'Inspirer profondément le parfum 3 fois après application',
      'Renouveler toutes les 1-2h les premiers jours',
    ],
    bonus: 'La Camomille Romaine est considérée comme l\'une des HE les plus apaisantes pour les chocs émotionnels (action sur le système nerveux parasympathique). Le Néroli est traditionnellement utilisé contre la peur et l\'angoisse aiguë.',
    precautions: 'Si choc émotionnel important (deuil, traumatisme), consulter un psychologue. L\'aromathérapie est un soutien, pas un substitut au soin psychologique. Allergie astéracées (Camomille).',
    source: 'Aromathérapie psycho-émotionnelle - École française',
  },

  {
    id: 'rec_bien_lacher_prise',
    titre: 'Lâcher-prise et méditation',
    categorie: 'Bien-être',
    sousCategorie: 'Méditation',
    indications: 'Favorise le lâcher-prise, ancrage, accompagne méditation et yoga',
    duree: 'Pendant la pratique',
    frequence: 'Avant méditation/yoga',
    ingredients: [
      { nom: 'HE Encens (Oliban)', quantite: '3 gouttes' },
      { nom: 'HE Bois de Hô', quantite: '2 gouttes' },
      { nom: 'HE Patchouli', quantite: '2 gouttes' },
      { nom: 'HE Lavande Vraie', quantite: '2 gouttes' },
    ],
    etapes: [
      'Diffuser les 9 gouttes dans la pièce 10 min avant la pratique',
      'Inspirer profondément avant de commencer (ancrage olfactif)',
      'Possibilité : 1 goutte Encens + 1 goutte Patchouli sur le 3ème œil (front) avec HV Jojoba',
      'Pratique régulière conseillée pour effet cumulé',
    ],
    bonus: 'L\'Encens (Boswellia) est utilisé depuis 5000 ans pour la méditation et la spiritualité. Effet démontré sur l\'apaisement de l\'esprit (effet sur les ions calcium dans le cerveau).',
    precautions: 'Patchouli, Encens : éviter 1er trimestre grossesse. Test cutané si application sur peau.',
    source: 'Études sur l\'Encens et la méditation - PubMed',
  },

  {
    id: 'rec_bien_humeur_hivernale',
    titre: 'Humeur hivernale (manque de lumière)',
    categorie: 'Bien-être',
    sousCategorie: 'Saisonnier',
    indications: 'Soutien de l\'humeur en période de manque de lumière (TAS - dépression saisonnière légère)',
    duree: 'Cure octobre à mars',
    frequence: 'Matin (15-30 min)',
    ingredients: [
      { nom: 'HE Pamplemousse', quantite: '5 gouttes' },
      { nom: 'HE Citron Jaune Zest', quantite: '4 gouttes' },
      { nom: 'HE Mandarine Zest', quantite: '3 gouttes' },
      { nom: 'HE Bois de Hô', quantite: '2 gouttes' },
    ],
    etapes: [
      'Diffuser le matin pendant 15-30 minutes (au lever)',
      'Idéalement avec une lampe de luminothérapie pour effet renforcé',
      'Compléter avec marche extérieure 20-30 min/jour (lumière naturelle = meilleur antidépresseur)',
      'Cure complète d\'octobre à mars',
    ],
    bonus: 'Les agrumes (Pamplemousse, Citron, Mandarine) sont riches en limonène, molécule étudiée pour son effet antidépresseur léger. À combiner avec luminothérapie + activité physique pour effets optimaux.',
    precautions: 'Tous les Zests sont photosensibilisants : pas d\'application cutanée avant exposition solaire. Si dépression saisonnière avérée, consulter un médecin (luminothérapie médicale + suivi).',
    source: 'Études sur le limonène et l\'humeur - PubMed',
  },

  {
    id: 'rec_bien_colere',
    titre: 'Apaisement de la colère et frustration',
    categorie: 'Bien-être',
    sousCategorie: 'Émotions',
    indications: 'Calme la colère, l\'irritabilité, les tensions émotionnelles',
    duree: 'Selon besoin',
    frequence: 'Aux moments de tension',
    ingredients: [
      { nom: 'HE Ylang-Ylang Totum', quantite: '2 gouttes' },
      { nom: 'HE Camomille Romaine', quantite: '2 gouttes' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '3 gouttes' },
    ],
    etapes: [
      'Diffuser 7 gouttes dans la pièce',
      'OU : Stick inhalateur, 3 inspirations profondes',
      'OU : 2 gouttes Ylang sur poignets, frotter et inspirer 3 fois',
      'Pratiquer 5 minutes de respiration cohérence cardiaque (5/5)',
    ],
    bonus: 'L\'Ylang-Ylang ralentit le rythme cardiaque (effet hypotenseur) et apaise la colère. Le Petit-Grain équilibre les émotions et calme les pensées négatives.',
    precautions: 'Ylang-Ylang : peut donner mal de tête à forte dose. Camomille : allergie astéracées possible. Si colère chronique, consulter un thérapeute.',
    source: 'Études sur Ylang-Ylang et hypotension - Journal of Ethnopharmacology',
  },

  {
    id: 'rec_bien_libido',
    titre: 'Soutien de la libido',
    categorie: 'Bien-être',
    sousCategorie: 'Vitalité',
    indications: 'Soutient la libido, dynamise, action sensuelle',
    duree: 'Selon désir',
    frequence: 'Soirée, ponctuel',
    ingredients: [
      { nom: 'HV de Vanille (macérât)', quantite: '30 ml' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '1% (6 gouttes)' },
      { nom: 'HE Gingembre', quantite: '0,5% (3 gouttes)' },
      { nom: 'HE Bois de Hô', quantite: '0,5% (3 gouttes)' },
    ],
    etapes: [
      'Mélanger les ingrédients',
      'Massage corps en soirée (zones préférées)',
      'OU : diffusion 10-15 minutes dans la chambre',
      'Possibilité : ajouter 1 goutte Rose de Damas pour version luxe',
    ],
    bonus: 'L\'Ylang-Ylang est l\'HE de la séduction par excellence (utilisée traditionnellement dans les rituels de mariage en Indonésie). Le Gingembre apporte tonus et chaleur.',
    precautions: 'Gingembre : peut irriter peaux sensibles, faire test cutané. Ylang-Ylang : usage modéré (puissant). Éviter 1er trimestre grossesse.',
    source: 'Aromathérapie traditionnelle - Pranarôm, Compagnie des Sens',
  },

  {
    id: 'rec_bien_grossesse_zen',
    titre: 'Sérénité de la grossesse (à partir du 4ème mois)',
    categorie: 'Bien-être',
    sousCategorie: 'Grossesse',
    indications: 'Apaise les angoisses liées à la grossesse, favorise le lien mère-bébé',
    duree: 'À partir du 4ème mois',
    frequence: 'Quotidien',
    ingredients: [
      { nom: 'HE Mandarine Zest', quantite: '3 gouttes' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '2 gouttes' },
      { nom: 'HE Lavande Vraie', quantite: '2 gouttes' },
    ],
    etapes: [
      'Diffusion uniquement (pas d\'application cutanée pour la grossesse)',
      '15-20 minutes par jour',
      'Idéalement le soir avant le coucher pour favoriser le sommeil',
      'Possibilité : respirer le flacon ouvert 30 secondes',
    ],
    bonus: 'Synergie ultra-douce, validée pour la grossesse (à partir du 4ème mois). Le Petit-Grain est traditionnellement utilisé pour les "petites peurs" de la grossesse.',
    precautions: 'JAMAIS d\'HE au 1er trimestre. À partir du 4ème mois : diffusion uniquement avec ces 3 HE testées. Mandarine Zest photosensibilisante. Demander avis sage-femme/gynéco.',
    source: 'Aromathérapie et grossesse - Festy D., école française',
  },

  {
    id: 'rec_bien_panique',
    titre: 'Crise de panique - urgence',
    categorie: 'Bien-être',
    sousCategorie: 'Anxiété',
    indications: 'Apaisement immédiat lors d\'une crise d\'angoisse ou panique',
    duree: 'Pendant la crise',
    frequence: 'À chaque crise',
    ingredients: [
      { nom: 'HE Lavande Vraie', quantite: '3 gouttes' },
      { nom: 'HE Camomille Romaine', quantite: '2 gouttes' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '2 gouttes' },
      { nom: 'Roll-on vide ou stick inhalateur', quantite: '1' },
    ],
    etapes: [
      'Préparer un roll-on : HE + HV de Noyau d\'Abricot (5 ml)',
      'Toujours en avoir un dans son sac/poche',
      'En cas de crise : appliquer sur poignets et tempes',
      'Inspirer profondément 5 fois en comptant : 4 sec inspiration, 6 sec expiration',
      'Continuer la respiration jusqu\'à apaisement',
    ],
    bonus: 'Plusieurs études cliniques sur la Lavande (linalol) montrent une action anxiolytique comparable à certains benzodiazépines mais sans effets secondaires. Le rituel olfactif crée un "ancrage" qui aide à reprendre contrôle.',
    precautions: 'Si crises de panique fréquentes/intenses, consulter un psychologue ou psychiatre. L\'aromathérapie est un soutien, pas un traitement. Bergamote photosensibilisante.',
    source: 'Études cliniques Silexan (lavande) - Phytomedicine, multiples publications',
  },

  {
    id: 'rec_bien_motivation',
    titre: 'Motivation et énergie matinale',
    categorie: 'Bien-être',
    sousCategorie: 'Énergie',
    indications: 'Booste l\'énergie matinale, lutte contre la procrastination',
    duree: 'Quotidien matin',
    frequence: 'Matin',
    ingredients: [
      { nom: 'HE Citron Jaune Zest', quantite: '4 gouttes' },
      { nom: 'HE Menthe Poivrée', quantite: '2 gouttes' },
      { nom: 'HE Romarin à Cinéole', quantite: '3 gouttes' },
      { nom: 'HE Pamplemousse', quantite: '3 gouttes' },
    ],
    etapes: [
      'Diffuser 12 gouttes le matin pendant la routine matinale (15 min)',
      'OU : 1 goutte Menthe sur les poignets (frotter + inspirer)',
      'Idéalement combiner avec douche fraîche et musique énergisante',
      'NE PAS utiliser après 16h (effet stimulant)',
    ],
    bonus: 'La Menthe Poivrée augmente la vigilance et la performance cognitive (études). Les agrumes améliorent l\'humeur (limonène).',
    precautions: 'Menthe Poivrée et Romarin INTERDITS moins de 7 ans, grossesse, épilepsie, hypertension. Zests photosensibilisants : pas avant exposition solaire si application cutanée.',
    source: 'Études cognition + Menthe Poivrée - International Journal of Neuroscience',
  },

  {
    id: 'rec_bien_digestion_emotion',
    titre: 'Ventre noué (digestion émotionnelle)',
    categorie: 'Bien-être',
    sousCategorie: 'Émotions',
    indications: 'Apaise les tensions abdominales liées au stress, ballonnements émotionnels',
    duree: 'Selon besoin',
    frequence: 'Après les repas ou en période de stress',
    ingredients: [
      { nom: 'HV de Noyau d\'Abricot', quantite: '15 ml' },
      { nom: 'HE Basilic Tropical', quantite: '5 gouttes' },
      { nom: 'HE Lavande Vraie', quantite: '5 gouttes' },
      { nom: 'HE Menthe Poivrée', quantite: '3 gouttes' },
    ],
    etapes: [
      'Préparer le mélange dans un flacon roll-on',
      'Masser le ventre dans le sens des aiguilles d\'une montre 5 minutes',
      'Inspirer profondément pendant le massage',
      'Possibilité : appliquer aussi sur le plexus solaire',
    ],
    bonus: 'Le Basilic Tropical est l\'HE digestive par excellence, particulièrement efficace pour les troubles digestifs liés au stress. La Lavande relaxe le système nerveux entérique (le "deuxième cerveau").',
    precautions: 'Menthe Poivrée et Basilic INTERDITS moins de 7 ans, grossesse, épilepsie. Test cutané au préalable.',
    source: 'Aromathérapie digestive - Faucon M.',
  },

  {
    id: 'rec_bien_libido_femme',
    titre: 'Équilibre hormonal féminin (cycles)',
    categorie: 'Bien-être',
    sousCategorie: 'Cycle féminin',
    indications: 'Soutien des cycles féminins (SPM, ménopause), équilibre émotionnel hormonal',
    duree: 'Cure 21 jours',
    frequence: 'Soir',
    ingredients: [
      { nom: 'HV Onagre ou Noyau d\'Abricot', quantite: '30 ml' },
      { nom: 'HE Géranium Rosat Bourbon', quantite: '1% (6 gouttes)' },
      { nom: 'HE Ylang-Ylang Totum', quantite: '1% (6 gouttes)' },
      { nom: 'HE Petit-Grain Bigarade', quantite: '1% (6 gouttes)' },
    ],
    etapes: [
      'Préparer le mélange dans un flacon teinté',
      'Le soir : massage du bas-ventre et bas du dos',
      'Cure 21 jours du 14ème jour du cycle au début des règles',
      'Pour la ménopause : tous les jours en cure de 3 semaines puis pause 1 semaine',
    ],
    bonus: 'Le Géranium Rosat est régulateur hormonal doux. À combiner avec Sauge Sclarée (mais ATTENTION : contre-indiquée si antécédent cancer hormono-dépendant).',
    precautions: 'CONTRE-INDIQUÉ grossesse, allaitement, antécédent cancer hormono-dépendant. Géranium éviter 1er trimestre. Toujours consulter un médecin/gynécologue.',
    source: 'Aromathérapie féminine - Festy D., école française',
  },

  {
    id: 'rec_bien_addictions',
    titre: 'Soutien aux addictions (sucre, écrans)',
    categorie: 'Bien-être',
    sousCategorie: 'Sevrage',
    indications: 'Soutien lors d\'envies compulsives (sucre, écrans, grignotages)',
    duree: 'Selon besoin',
    frequence: 'À chaque envie compulsive',
    ingredients: [
      { nom: 'HE Cannelle de Ceylan (écorce)', quantite: '2 gouttes' },
      { nom: 'HE Menthe Poivrée', quantite: '3 gouttes' },
      { nom: 'HE Citron Jaune Zest', quantite: '5 gouttes' },
      { nom: 'Stick inhalateur', quantite: '1' },
    ],
    etapes: [
      'Préparer le stick avec les 10 gouttes',
      'À chaque envie compulsive : 3 inspirations profondes',
      'Boire un grand verre d\'eau immédiatement après',
      'Renouveler le stick toutes les 4 semaines',
    ],
    bonus: 'La Cannelle régule la glycémie et coupe les envies de sucre (études). Combiner avec hydratation, sport, et identification émotionnelle de l\'envie compulsive.',
    precautions: 'Cannelle INTERDITE en application cutanée pure (très dermocaustique). Menthe Poivrée : interdite enfants moins de 7 ans, grossesse, épilepsie. Inhalation uniquement.',
    source: 'Études Cannelle et glycémie - Diabetes Care',
  },

];

// Fusion des 3 packs (base + pro + complémentaires) — total ~120 recettes.
// Déduplication par id : si un id existe dans plusieurs packs, on garde la première occurrence (base).
const _seenIds = new Set();
export const RECETTES_BIBLIOTHEQUE = [
  ...RECETTES_BASE,
  ...RECETTES_PRO_PACK,
  ...RECETTES_COMPLEMENTAIRES,
].filter(r => {
  if (!r?.id || _seenIds.has(r.id)) return false;
  _seenIds.add(r.id);
  return true;
});

export const CATEGORIES_RECETTES = [
  { key: 'Tous', label: 'Toutes' },
  { key: 'Bien-être', label: 'Bien-être' },
  { key: 'Visage', label: 'Visage' },
  { key: 'Cheveux', label: 'Cheveux' },
  { key: 'Corps', label: 'Corps' },
  { key: 'Minceur', label: 'Minceur' },
  { key: 'Toilette', label: 'Toilette' },
  { key: 'Homme', label: 'Homme' },
  { key: 'Maman', label: 'Maman' },
];
